import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, ShieldCheck } from "lucide-react";
import { acknowledgeDeviceAlert, getDeviceAlerts, getDeviceChanges, getDeviceInventory, getDeviceSnapshots } from "../../services/deviceService";
import type { AssetAlert, AssetChange, AssetInventory, Device } from "../../types/device";
const tabs=["Visão geral","Hardware","Sistema","Rede","Armazenamento","Segurança","Histórico"] as const;
const show=(v:unknown)=>v==null||v===""?"Não informado":typeof v==="object"?JSON.stringify(v):String(v);
const bytes=(v:unknown)=>typeof v==="number"?`${(v/1073741824).toFixed(2)} GB`:"Não informado";
function Rows({data}:{data?:Record<string,unknown>}){return <div className="grid gap-2 sm:grid-cols-2">{Object.entries(data||{}).map(([k,v])=><div key={k} className="rounded-xl border p-3"><small className="block font-black uppercase text-zinc-400">{k}</small><b className="break-words text-sm">{show(v)}</b></div>)}</div>}
function Cards({items}:{items?:Record<string,unknown>[]}){return items?.length?<div className="grid gap-3 md:grid-cols-2">{items.map((x,i)=><div key={i} className="rounded-xl bg-zinc-50 p-3"><Rows data={x}/></div>)}</div>:<p className="text-sm text-zinc-500">Nenhuma informação recebida.</p>}
export function AssetInventoryPanel({device}:{device:Device}){
 const [tab,setTab]=useState<(typeof tabs)[number]>(tabs[0]),[inv,setInv]=useState<AssetInventory|null>(null),[changes,setChanges]=useState<AssetChange[]>([]),[alerts,setAlerts]=useState<AssetAlert[]>([]),[snapshots,setSnapshots]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let ok=true;Promise.all([getDeviceInventory(device.id),getDeviceChanges(device.id),getDeviceAlerts(device.id),getDeviceSnapshots(device.id)]).then(([i,c,a,s])=>{if(ok){setInv(i);setChanges(c);setAlerts(a);setSnapshots(s.length)}}).catch(e=>ok&&setError(e.message)).finally(()=>ok&&setLoading(false));return()=>{ok=false}},[device.id]);
 const ack=async(a:AssetAlert)=>{await acknowledgeDeviceAlert(device.id,a.id);setAlerts(x=>x.map(y=>y.id===a.id?{...y,acknowledged:true}:y))};
 if(loading)return <section className="rounded-2xl border bg-white p-5">Carregando ficha técnica...</section>;
 if(error)return <section className="rounded-2xl border border-red-200 bg-red-50 p-5 text-red-700">{error}</section>;
 if(!inv)return <section className="rounded-2xl border bg-white p-6"><h2 className="font-black">Inventário automático ainda não recebido</h2><p className="text-sm text-zinc-500">Atualize ou instale o agente para preencher a ficha técnica e iniciar o histórico.</p></section>;
 const active=alerts.filter(a=>a.active&&!a.acknowledged),health=device.communicationStatus==="no_communication"?"Sem comunicação":active.some(a=>a.severity==="CRITICAL")?"Crítico":active.length?"Atenção":"Saudável";
 return <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-black">Ficha técnica e histórico</h2><p className="text-xs text-zinc-500">{new Date(inv.collectedAt).toLocaleString("pt-BR")} · agente {inv.agentVersion} · schema {inv.schemaVersion}</p></div><b className="rounded-full bg-blue-50 px-3 py-1 text-xs text-blue-700">{health}</b></div><div className="mt-4 flex overflow-x-auto border-b">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`whitespace-nowrap border-b-2 px-3 py-2 text-xs font-black ${tab===t?"border-blue-600 text-blue-600":"border-transparent text-zinc-500"}`}>{t}</button>)}</div><div className="mt-4">
 {tab==="Visão geral"&&<><div className="mb-4 grid gap-2 sm:grid-cols-3"><Tile k="Comunicação" v={device.communicationStatus||"Sem dados"}/><Tile k="Alertas ativos" v={String(active.length)}/><Tile k="Snapshots" v={String(snapshots)}/></div><Rows data={inv.computer}/></>}
 {tab==="Hardware"&&<div className="space-y-4"><h3 className="font-black">Processadores</h3><Cards items={inv.processors}/><h3 className="font-black">Memória · {bytes(inv.memory?.totalBytes)}</h3><Cards items={inv.memory?.modules}/><Rows data={{...(inv.motherboard||{}),...(inv.bios||{})}}/></div>}
 {tab==="Sistema"&&<><Rows data={inv.operatingSystem}/><h3 className="my-3 font-black">Atualizações recentes</h3><Cards items={inv.updates}/></>}
 {tab==="Rede"&&<Rows data={inv.network}/>} {tab==="Armazenamento"&&<div className="space-y-4"><b>Total {bytes(inv.storage?.totalBytes)} · Livre {bytes(inv.storage?.freeBytes)}</b><Cards items={inv.storage?.physicalDisks}/><Cards items={inv.storage?.volumes}/></div>}
 {tab==="Segurança"&&<div className="space-y-3">{Object.entries(inv.security||{}).map(([k,v])=><div key={k} className="rounded-xl border p-3"><b className="flex gap-2 capitalize"><ShieldCheck size={17}/>{k}: {v.status||"UNKNOWN"}</b><Rows data={v}/></div>)}{alerts.map(a=><div key={a.id} className="flex justify-between gap-3 rounded-xl bg-amber-50 p-3 text-sm"><span><b>{a.title}</b><small className="block">{a.message}</small></span>{!a.acknowledged&&<button onClick={()=>ack(a)} className="rounded-lg bg-white px-3 font-black">Reconhecer</button>}</div>)}</div>}
 {tab==="Histórico"&&<div className="space-y-3">{changes.length?changes.map(c=><div key={c.id} className="flex gap-3 rounded-xl border p-3"><AlertTriangle size={17}/><div><b>{c.field}</b><p className="break-all text-xs text-zinc-500">{show(c.oldValue)} → {show(c.newValue)}</p><small>{new Date(c.detectedAt).toLocaleString("pt-BR")}</small></div></div>):<p className="flex gap-2 text-emerald-700"><CheckCircle2/>Nenhuma alteração após a primeira coleta.</p>}</div>}
 </div></section>}
function Tile({k,v}:{k:string;v:string}){return <div className="rounded-xl bg-zinc-50 p-3"><small className="font-black uppercase text-zinc-400">{k}</small><b className="block">{v}</b></div>}
