import { Activity, AlertTriangle, Clock3, Cpu, Database, Gauge, HardDrive, History, Laptop, MemoryStick, Network, RefreshCw, ShieldCheck, Ticket, Wifi, X } from "lucide-react";
import type { ReactNode } from "react";
import type { Device } from "../../types/device";

function formatUptime(hours=0){const days=Math.floor(hours/24),rest=Math.floor(hours%24);return days?`${days}d ${rest}h`:`${rest}h`;}
function tone(value:number){return value>=85?"bg-red-500":value>=70?"bg-amber-500":"bg-emerald-500";}
function MetricRing({label,value,detail,icon}:{label:string;value:number;detail:string;icon:ReactNode}){return <section className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h3 className="font-black text-zinc-800">{label}</h3><span className="text-blue-600">{icon}</span></div><div className="mt-5 flex items-center gap-5"><div className="grid h-28 w-28 shrink-0 place-items-center rounded-full" style={{background:`conic-gradient(${value>=85?'#ef4444':value>=70?'#f59e0b':'#22c55e'} ${Math.min(100,value)*3.6}deg,#e4e4e7 0)`}}><div className="grid h-20 w-20 place-items-center rounded-full bg-white text-2xl font-black">{Math.round(value)}%</div></div><div className="min-w-0 flex-1"><p className="break-words text-sm font-bold text-zinc-700">{detail}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-zinc-100"><div className={`h-full ${tone(value)}`} style={{width:`${Math.min(100,value)}%`}}/></div><p className={`mt-3 text-xs font-black ${value>=85?'text-red-600':value>=70?'text-amber-600':'text-emerald-600'}`}>{value>=85?'Nível crítico':value>=70?'Requer atenção':'Operação normal'}</p></div></div></section>}

export function DeviceDiagnostics({device,onClose,onRefresh,onAction,refreshing}:{device:Device;onClose:()=>void;onRefresh:()=>void;onAction:(type:string,device:Device)=>void;refreshing?:boolean}){
  const issues=[device.cpuUsage>=85&&"Uso elevado de processador",device.ramUsage>=85&&"Uso elevado de memória",device.diskUsage>=85&&"Espaço em disco crítico",device.antivirusAtualizado===false&&"Antivírus desatualizado",device.firewallEnabled===false&&"Firewall desativado"].filter(Boolean) as string[];
  const stable=device.status==="online"&&issues.length===0;
  return <div className="fixed inset-0 z-[110] overflow-y-auto bg-[#f3f6fa] text-zinc-900"><header className="sticky top-0 z-20 border-b border-zinc-200 bg-[#111c2d] text-white shadow-lg"><div className="mx-auto flex max-w-[1500px] flex-wrap items-center gap-4 px-5 py-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-600"><ShieldCheck/></span><div className="min-w-0 flex-1"><p className="text-[10px] font-black uppercase tracking-[.22em] text-blue-300">Smart HelpDesk</p><h1 className="truncate text-xl font-black">Diagnóstico da Estação</h1></div><div className="hidden text-right text-xs text-slate-300 sm:block"><p className="font-black text-emerald-400">● {device.status==="offline"?"Sem comunicação":"Conectado"}</p><p>{device.usuario}</p></div><button onClick={onRefresh} disabled={refreshing} className="flex h-10 items-center gap-2 rounded-xl bg-blue-600 px-4 text-xs font-black disabled:opacity-60"><RefreshCw size={15} className={refreshing?"animate-spin":""}/>Atualizar dados</button><button onClick={onClose} aria-label="Fechar diagnóstico" className="grid h-10 w-10 place-items-center rounded-xl border border-white/15"><X/></button></div></header>
  <main className="mx-auto max-w-[1500px] space-y-4 p-4 sm:p-6"><section className="grid gap-3 rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm md:grid-cols-4"><Summary icon={<Laptop/>} label="Computador" value={device.hostname} sub={device.patrimonio}/><Summary icon={<Database/>} label="Sistema operacional" value={device.sistemaOperacional} sub={device.processador}/><Summary icon={<Clock3/>} label="Tempo ligado" value={device.uptimeHours?formatUptime(device.uptimeHours):"Aguardando coleta"} sub={device.lastBoot?`Desde ${new Date(device.lastBoot).toLocaleString("pt-BR")}`:"Disponível na próxima coleta"}/><Summary icon={<Activity/>} label="Último diagnóstico" value={new Date(device.ultimoHeartbeat).toLocaleDateString("pt-BR")} sub={new Date(device.ultimoHeartbeat).toLocaleTimeString("pt-BR")}/></section>
  <div className="grid gap-4 xl:grid-cols-3"><MetricRing label="Uso do processador" value={device.cpuUsage} detail={device.processador} icon={<Cpu/>}/><MetricRing label="Uso de memória RAM" value={device.ramUsage} detail={`${device.ramTotal} GB instalados`} icon={<MemoryStick/>}/><MetricRing label="Armazenamento" value={device.diskUsage} detail={device.armazenamento} icon={<HardDrive/>}/></div>
  <div className="grid gap-4 xl:grid-cols-3"><Panel title="Estabilidade do sistema" icon={<Gauge/>}><div className={`rounded-2xl p-5 ${stable?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}><p className="text-2xl font-black">{stable?'Estável':'Requer atenção'}</p><p className="mt-1 text-sm">Resultado baseado no último diagnóstico recebido.</p></div><StatusRow label="Antivírus" ok={device.antivirusAtualizado!==false}/><StatusRow label="Firewall" ok={device.firewallEnabled!==false} unknown={device.firewallEnabled==null}/></Panel><Panel title="Rede" icon={<Wifi/>}><Info label="Interface" value={device.networkType||"Não informada"}/><Info label="IP local" value={device.ip}/><Info label="MAC" value={device.mac||"Não informado"}/><Info label="Velocidade" value={device.linkSpeed||"Não informada"}/><div className="rounded-xl bg-blue-50 p-3 text-xs font-bold text-blue-700"><Network size={15} className="mr-2 inline"/>Dados técnicos da conexão corporativa.</div></Panel><Panel title={`Alertas (${issues.length})`} icon={<AlertTriangle/>}>{issues.length?issues.map(issue=><div key={issue} className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-bold text-amber-800"><AlertTriangle size={17} className="shrink-0"/>{issue}</div>):<div className="rounded-2xl bg-emerald-50 p-5 text-sm font-bold text-emerald-700"><ShieldCheck className="mb-2"/>Nenhuma anormalidade detectada na última coleta.</div>}<p className="text-[11px] leading-5 text-zinc-500">Não exibimos processos, arquivos, navegação, senhas, teclas, áudio, câmera ou GPS.</p></Panel></div>
  <section className="grid gap-3 rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm md:grid-cols-3"><button onClick={()=>onAction("historico",device)} className="flex items-center justify-center gap-2 rounded-xl border p-4 text-sm font-black"><History size={18}/>Ver histórico</button><button onClick={()=>onAction("chamado",device)} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 p-4 text-sm font-black text-white"><Ticket size={18}/>Abrir chamado com diagnóstico</button><button onClick={onRefresh} className="flex items-center justify-center gap-2 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm font-black text-blue-700"><RefreshCw size={18}/>Consultar servidor</button></section><p className="pb-4 text-center text-[11px] text-zinc-500"><ShieldCheck size={13} className="mr-1 inline"/>Informações técnicas protegidas por perfil de acesso e usadas para suporte, segurança e inventário.</p></main></div>;
}
function Summary({icon,label,value,sub}:{icon:ReactNode;label:string;value:string;sub:string}){return <div className="flex min-w-0 gap-3 md:border-r md:last:border-0"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600">{icon}</span><div className="min-w-0"><p className="text-[10px] font-black uppercase tracking-wide text-zinc-400">{label}</p><b className="block truncate text-sm">{value}</b><small className="block truncate text-zinc-500">{sub}</small></div></div>}
function Panel({title,icon,children}:{title:string;icon:ReactNode;children:ReactNode}){return <section className="space-y-3 rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><h3 className="flex items-center gap-2 font-black text-zinc-800"><span className="text-blue-600">{icon}</span>{title}</h3>{children}</section>}
function Info({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-3 border-b border-zinc-100 py-2 text-sm"><span className="text-zinc-500">{label}</span><b className="text-right">{value}</b></div>}
function StatusRow({label,ok,unknown}:{label:string;ok:boolean;unknown?:boolean}){return <div className="flex justify-between rounded-xl border border-zinc-100 p-3 text-sm"><b>{label}</b><span className={unknown?'text-zinc-400':ok?'font-black text-emerald-600':'font-black text-red-600'}>{unknown?'Aguardando coleta':ok?'Protegido':'Requer atenção'}</span></div>}
