/**
 * Responsabilidade: Componente de interface de device details; apresenta dados e interações do usuário.
 */
import { Activity, Clock3, History, MapPin, ShieldCheck, Ticket, X } from "lucide-react";
import type { Device } from "../../types/device";

const statusMeta={online:["Online","bg-emerald-50 text-emerald-700 border-emerald-200"],warning:["Atenção","bg-amber-50 text-amber-700 border-amber-200"],offline:["Offline","bg-red-50 text-red-700 border-red-200"]} as const;
function Metric({label,value}:{label:string;value:number}){const color=value>=85?"bg-red-500":value>=70?"bg-amber-500":"bg-blue-600";return <div><div className="mb-1 flex justify-between text-xs font-black"><span>{label}</span><span>{Math.round(value)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-zinc-100"><div className={`h-full ${color}`} style={{width:`${value}%`}}/></div></div>}

export function DeviceDetails({device,onAction,onClose}:{device?:Device|null;onAction:(action:string,device:Device)=>void;onClose?:()=>void}){
  if(!device)return null;
  const [statusLabel,statusClass]=statusMeta[device.status];
  const rows=[["Patrimônio",device.patrimonio],["Município",device.municipio],["Unidade",device.unidade],["IP",device.ip],["Usuário",device.usuario],["Sistema",device.sistemaOperacional],["RAM",`${device.ramTotal} GB`],["Armazenamento",device.armazenamento]];
  return <aside className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><p className="text-[11px] font-black uppercase tracking-widest text-blue-600">Computador selecionado</p>{onClose&&<button onClick={onClose}><X size={16}/></button>}</div><div className="mt-2 flex justify-between"><div><h3 className="text-xl font-black">{device.hostname}</h3><small className="text-zinc-400">{device.deviceId}</small></div><span className={`h-fit rounded-full border px-3 py-1 text-xs font-black ${statusClass}`}>{statusLabel}</span></div><div className="mt-4 divide-y">{rows.map(([label,value])=><div key={label} className="flex justify-between gap-3 py-2 text-sm"><span className="text-zinc-500">{label}</span><b className="text-right">{value}</b></div>)}</div><div className="mt-3 rounded-xl bg-zinc-50 p-3"><p className="flex items-center gap-2 text-xs text-zinc-500"><Clock3 size={14}/>Último diagnóstico</p><b className="text-sm">{new Date(device.ultimoHeartbeat).toLocaleString("pt-BR")}</b><p className="mt-1 text-[10px] text-zinc-500">O resultado permanece até a próxima coleta ou atualização técnica.</p></div><div className="mt-4 space-y-3"><Metric label="CPU" value={device.cpuUsage}/><Metric label="RAM" value={device.ramUsage}/><Metric label="Disco" value={device.diskUsage}/></div><div className="mt-5"><p className="mb-2 flex items-center gap-2 text-[11px] font-black text-zinc-500"><ShieldCheck size={14}/>ATUALIZAÇÃO TÉCNICA</p><div className="grid grid-cols-3 gap-1.5">{([['online','Online'],['warning','Atenção'],['offline','Offline']] as const).map(([value,label])=><button key={value} onClick={()=>onAction(`status:${value}`,device)} disabled={device.status===value} className="rounded-lg border px-1 py-2 text-[10px] font-black disabled:border-blue-200 disabled:bg-blue-50 disabled:text-blue-700">{label}</button>)}</div></div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>onAction("diagnostico",device)} className="col-span-2 rounded-xl bg-slate-900 p-3 text-xs font-black text-white"><Activity size={15} className="mr-2 inline"/>Abrir diagnóstico completo</button><button onClick={()=>onAction("historico",device)} className="col-span-2 rounded-xl border p-2.5 text-xs font-black"><History size={15} className="mr-2 inline"/>Histórico de diagnósticos</button><button onClick={()=>window.dispatchEvent(new CustomEvent("asset-location-correct",{detail:device}))} className="col-span-2 rounded-xl border border-blue-200 bg-blue-50 p-2.5 text-xs font-black text-blue-700"><MapPin size={15} className="mr-2 inline"/>Corrigir unidade/localização</button><button onClick={()=>onAction("chamado",device)} className="col-span-2 rounded-xl bg-blue-600 p-3 text-xs font-black text-white"><Ticket size={15} className="mr-2 inline"/>Abrir chamado para este ativo</button></div></aside>;
}
