/**
 * Responsabilidade: aba Relatórios do portal: filtros do mês, prévia e download.
 */
import { Download, Filter, RefreshCw, Search, ShieldCheck } from "lucide-react";
import { ticketStatusLabel } from "../../../domain/ticketStatus";
import type { PainelPortal } from "../useUserPortal";

export function AbaRelatorios({ portal }: { portal: PainelPortal }) {
  const { mesRelatorio, setMesRelatorio, statusRelatorio, setStatusRelatorio, tipoRelatorio, setTipoRelatorio, buscaRelatorio, setBuscaRelatorio, formatoBaixando, intervaloRelatorio, statusDisponiveisRelatorio, tiposDisponiveisRelatorio, chamadosRelatorioFiltrados, podeBaixarRelatorios, baixarRelatorioDoMes } = portal;
  return (
    <section className="space-y-3">
      <div className="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm">
        <header className="flex items-center gap-3 border-b border-zinc-100 px-5 py-4"><span className="grid h-9 w-9 place-items-center rounded-lg bg-blue-50 text-blue-700"><Filter size={17}/></span><div><h2 className="text-base font-black">Filtros do relatório</h2><p className="text-xs text-zinc-500">Os filtros abaixo também serão aplicados ao arquivo baixado.</p></div></header>
        <div className="grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-4">
          <label><span className="mb-1.5 block text-[10px] font-black uppercase text-zinc-500">Mês</span><input type="month" required value={mesRelatorio} max={new Date().toISOString().slice(0, 7)} onChange={(event) => { if (event.target.value) setMesRelatorio(event.target.value); }} className="h-10 w-full rounded-lg border border-zinc-200 bg-white px-3 text-sm font-bold outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100"/></label>
          <label><span className="mb-1.5 block text-[10px] font-black uppercase text-zinc-500">Status</span><select value={statusRelatorio} onChange={(event) => setStatusRelatorio(event.target.value)} className="h-10 w-full rounded-lg border border-zinc-200 bg-white px-3 text-sm outline-none focus:border-blue-400"><option value="">Todos</option>{statusDisponiveisRelatorio.map((status) => <option key={status} value={status}>{ticketStatusLabel(status)}</option>)}</select></label>
          <label><span className="mb-1.5 block text-[10px] font-black uppercase text-zinc-500">Tipo</span><select value={tipoRelatorio} onChange={(event) => setTipoRelatorio(event.target.value)} className="h-10 w-full rounded-lg border border-zinc-200 bg-white px-3 text-sm outline-none focus:border-blue-400"><option value="">Todos</option>{tiposDisponiveisRelatorio.map((tipo) => <option key={tipo}>{tipo}</option>)}</select></label>
          <label><span className="mb-1.5 block text-[10px] font-black uppercase text-zinc-500">Pesquisar</span><span className="flex h-10 items-center gap-2 rounded-lg border border-zinc-200 px-3 focus-within:border-blue-400"><Search size={15} className="text-zinc-400"/><input value={buscaRelatorio} onChange={(event) => setBuscaRelatorio(event.target.value)} placeholder="Número, título..." className="min-w-0 flex-1 bg-transparent text-sm outline-none"/></span></label>
        </div>
        <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-zinc-100 bg-zinc-50/70 px-5 py-3"><span className="text-xs text-zinc-500">{new Date(`${intervaloRelatorio.data_inicio}T12:00:00`).toLocaleDateString("pt-BR")} — {new Date(`${intervaloRelatorio.data_fim}T12:00:00`).toLocaleDateString("pt-BR")}</span><button type="button" onClick={() => { setStatusRelatorio(""); setTipoRelatorio(""); setBuscaRelatorio(""); }} className="h-9 rounded-lg border border-zinc-200 bg-white px-4 text-xs font-black text-zinc-600 hover:bg-zinc-100">Limpar filtros</button></footer>
      </div>

      <div className="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm">
        <header className="flex flex-wrap items-center justify-between gap-3 border-b border-zinc-100 px-5 py-4"><div><h3 className="text-base font-black">Resultado da pesquisa</h3><p className="mt-0.5 text-xs text-zinc-500">{chamadosRelatorioFiltrados.length} registro(s) encontrado(s)</p></div>{podeBaixarRelatorios ? <div className="flex flex-wrap gap-1.5">{(["csv", "excel", "pdf"] as const).map((formato) => <button key={formato} type="button" disabled={Boolean(formatoBaixando)} onClick={() => void baixarRelatorioDoMes(formato)} className="inline-flex h-9 items-center gap-1.5 rounded-lg bg-blue-600 px-3 text-xs font-black uppercase text-white hover:bg-blue-700 disabled:opacity-50">{formatoBaixando === formato ? <RefreshCw size={14} className="animate-spin"/> : <Download size={14}/>} {formato === "excel" ? "Excel" : formato.toUpperCase()}</button>)}</div> : <span className="text-xs font-bold text-amber-700">Sem permissão para exportar</span>}</header>
        <div className="overflow-x-auto">
          <table className="w-full min-w-[850px] text-left text-xs"><thead className="bg-zinc-50 text-[10px] uppercase tracking-wide text-zinc-500"><tr><th className="px-4 py-3">Chamado</th><th className="px-4 py-3">Título</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Prioridade</th><th className="px-4 py-3">Responsável</th><th className="px-4 py-3">Abertura</th></tr></thead><tbody className="divide-y divide-zinc-100">{chamadosRelatorioFiltrados.slice(0, 10).map((chamado) => <tr key={chamado.id} className="hover:bg-blue-50/40"><td className="whitespace-nowrap px-4 py-3 font-black text-blue-700">{chamado.numero_chamado || `#${chamado.id}`}</td><td className="max-w-72 truncate px-4 py-3 font-bold">{chamado.titulo}</td><td className="px-4 py-3">{ticketStatusLabel(chamado.status)}</td><td className="px-4 py-3">{chamado.prioridade || "—"}</td><td className="px-4 py-3">{chamado.responsavel_nome || chamado.responsavel || "Não atribuído"}</td><td className="whitespace-nowrap px-4 py-3">{chamado.criado_em ? new Date(chamado.criado_em).toLocaleDateString("pt-BR") : "—"}</td></tr>)}{!chamadosRelatorioFiltrados.length && <tr><td colSpan={6} className="px-4 py-12 text-center text-sm text-zinc-500">Nenhum chamado corresponde aos filtros selecionados.</td></tr>}</tbody></table>
        </div>
        <footer className="flex items-center justify-between border-t border-zinc-100 px-5 py-3 text-xs text-zinc-500"><span>Exibindo {Math.min(10, chamadosRelatorioFiltrados.length)} de {chamadosRelatorioFiltrados.length}</span><span className="flex items-center gap-1.5"><ShieldCheck size={14} className="text-emerald-600"/>Somente seus chamados</span></footer>
      </div>
    </section>
  );
}
