/**
 * Responsabilidade: Componente de interface de permission matrix page; apresenta dados e interações do usuário.
 */
import { useCallback, useEffect, useState } from "react";
import { Check, RefreshCw, ShieldCheck, X } from "lucide-react";
import { listarCatalogoPermissoes, obterPermissoesUsuario, type ApiUsuario, type PermissionDefinition, type PermissionKey } from "../services/api";

export function PermissionMatrixPage({ users, onEdit }: { users:ApiUsuario[]; onEdit:(user:ApiUsuario)=>void }) {
  const [catalog,setCatalog]=useState<PermissionDefinition[]>([]),[matrix,setMatrix]=useState<Record<number,PermissionKey[]>>({}),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const definitions=await listarCatalogoPermissoes();setCatalog(definitions);const rows=await Promise.all(users.map(async user=>[user.id,(await obterPermissoesUsuario(user.id)).permissions] as const));setMatrix(Object.fromEntries(rows))}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar acessos")}finally{setLoading(false)}},[users]);
  useEffect(()=>{void load()},[load]);
  return <div className="ds-page space-y-4"><section className="ds-panel p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-black"><ShieldCheck className="text-blue-600" size={20}/>Matriz de acessos</h2><p className="mt-1 text-xs text-slate-500">Permissões efetivas validadas pelo servidor, incluindo acessos padrão do perfil.</p></div><button className="ds-button ds-button--secondary inline-flex items-center gap-2" onClick={()=>void load()}><RefreshCw size={15} className={loading?"animate-spin":""}/>Atualizar</button></div></section>{error?<div className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>:null}<section className="ds-card overflow-auto"><table className="w-full min-w-[1100px] text-left text-xs"><thead className="sticky top-0 bg-slate-50"><tr><th className="p-3">Pessoa</th><th className="p-3">Perfil</th>{catalog.map(item=><th key={item.key} className="max-w-32 p-3 text-center" title={item.description}>{item.label}</th>)}</tr></thead><tbody className="divide-y">{users.map(user=><tr key={user.id} className="hover:bg-blue-50/40"><td className="p-3"><button onClick={()=>onEdit(user)} className="font-black text-blue-700 hover:underline">{user.nome}</button><span className="block text-[10px] text-slate-500">{user.email}</span></td><td className="p-3 font-bold capitalize">{user.perfil}</td>{catalog.map(item=>{const allowed=(matrix[user.id]||[]).includes(item.key);return <td key={item.key} className="p-3 text-center">{loading?<span className="text-slate-300">—</span>:allowed?<Check className="mx-auto text-emerald-600" size={17}/>:<X className="mx-auto text-slate-300" size={15}/>}</td>})}</tr>)}</tbody></table></section></div>;
}
