/**
 * Responsabilidade: Componente de interface de permission dialog; apresenta dados e interações do usuário.
 */
import { useEffect, useState } from "react";
import { BarChart3, Check, Download, FilePenLine, MapPinned, Settings, ShieldCheck, Ticket, UserCog, X } from "lucide-react";
import { atualizarPermissoesUsuario, listarCatalogoPermissoes, obterPermissoesUsuario, type ApiUsuario, type PermissionDefinition, type PermissionKey } from "../services/api";

const icons: Record<PermissionKey, typeof ShieldCheck> = { visualizar_dashboard: BarChart3, visualizar_relatorios: BarChart3, exportar_dados: Download, baixar_relatorios: Download, visualizar_patrimonio: MapPinned, administrar_ativos: MapPinned, gerenciar_chamados: Ticket, assumir_chamados: Ticket, delegar_chamados: UserCog, alterar_prioridade: Ticket, encerrar_chamados: Ticket, gerenciar_usuarios: UserCog, alterar_configuracoes: Settings, gerenciar_base: FilePenLine };

export function PermissionDialog({ user, dark, onClose, onSaved }: { user: ApiUsuario; dark?: boolean; onClose: () => void; onSaved?: () => void }) {
  const [catalog, setCatalog] = useState<PermissionDefinition[]>([]);
  const [selected, setSelected] = useState<PermissionKey[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { Promise.all([listarCatalogoPermissoes(), obterPermissoesUsuario(user.id)]).then(([items, current]) => { setCatalog(items); setSelected(current.permissions); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, [user.id]);
  const toggle = (key: PermissionKey) => setSelected((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key]);
  const save = async () => { setSaving(true); setError(""); try { await atualizarPermissoesUsuario(user.id, selected); onSaved?.(); onClose(); } catch (e) { setError(e instanceof Error ? e.message : "Erro ao salvar permissões"); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/45 p-3 backdrop-blur-sm sm:p-4" role="dialog" aria-modal="true" aria-labelledby="permission-dialog-title"><div className={`flex max-h-[calc(100dvh-24px)] w-full max-w-2xl flex-col overflow-hidden rounded-3xl border shadow-2xl sm:max-h-[calc(100dvh-32px)] ${dark ? "border-white/10 bg-[#101827] text-white" : "border-zinc-200 bg-white text-zinc-900"}`}><header className={`flex shrink-0 items-start justify-between gap-3 border-b p-4 sm:p-5 ${dark ? "border-white/10" : "border-zinc-100"}`}><div className="min-w-0"><h2 id="permission-dialog-title" className="flex items-center gap-2 text-lg font-black"><ShieldCheck size={20} className="shrink-0 text-blue-600"/>Permissões de acesso</h2><p className="mt-1 truncate text-sm opacity-60">{user.nome} • {user.email}</p></div><button type="button" onClick={onClose} aria-label="Fechar permissões" className="shrink-0 rounded-xl p-2 transition hover:bg-zinc-500/10"><X size={18}/></button></header><div className="min-h-0 flex-1 overflow-y-auto overscroll-contain p-4 sm:p-5"><p className="mb-4 text-sm opacity-65">Marque somente as funções necessárias. A permissão será validada também pelo servidor.</p>{loading ? <div className="py-10 text-center text-sm opacity-60">Carregando permissões...</div> : <div className="grid gap-3 sm:grid-cols-2">{catalog.map((permission) => { const Icon = icons[permission.key]; const active = selected.includes(permission.key); return <button key={permission.key} type="button" onClick={() => toggle(permission.key)} className={`relative flex gap-3 rounded-2xl border p-4 text-left transition ${active ? "border-blue-500 bg-blue-500/10 ring-2 ring-blue-500/10" : dark ? "border-white/10 hover:bg-white/5" : "border-zinc-200 hover:bg-zinc-50"}`}><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${active ? "bg-blue-600 text-white" : "bg-zinc-100 text-zinc-500"}`}><Icon size={18}/></span><span><span className="block text-sm font-black">{permission.label}</span><span className="mt-1 block text-xs leading-5 opacity-60">{permission.description}</span></span>{active && <Check size={16} className="absolute right-3 top-3 text-blue-600"/>}</button>; })}</div>}{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}</div><footer className={`flex shrink-0 flex-col-reverse gap-2 border-t p-4 sm:flex-row sm:justify-end sm:gap-3 sm:p-5 ${dark ? "border-white/10" : "border-zinc-100"}`}><button type="button" onClick={onClose} className="h-10 rounded-xl border border-zinc-300 px-4 text-sm font-bold">Cancelar</button><button type="button" onClick={save} disabled={loading || saving} className="h-10 rounded-xl bg-blue-600 px-5 text-sm font-bold text-white disabled:opacity-50">{saving ? "Salvando..." : "Salvar permissões"}</button></footer></div></div>;
}
