import { useEffect, useMemo, useState, type ReactNode } from "react";
import { BarChart3, CalendarDays, CheckCircle2, Clock3, Download, FileSpreadsheet, FileText, Gauge, ShieldCheck, Star, Users } from "lucide-react";
import { obterMetricasRelatorio, type ApiChamado, type FiltrosChamados, type ReportMetrics } from "../services/api";
import { isFinalTicketStatus, ticketStatusLabel } from "../domain/ticketStatus";

type Format = "csv" | "excel" | "pdf";
type Period = "7" | "30" | "90" | "365" | "all" | "custom";
type Props = { chamados: ApiChamado[]; dark: boolean; onDownload: (format: Format, filters: FiltrosChamados) => void };
const date = (value?: string) => { const result = value ? new Date(value) : null; return result && !Number.isNaN(result.getTime()) ? result : null; };
const owner = (ticket: ApiChamado) => ticket.responsavel_nome || ticket.responsavel || "Sem responsável";
const average = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null;
const elapsed = (start?: string, end?: string) => { const a = date(start); const b = date(end); return a && b ? Math.max(0, (b.getTime() - a.getTime()) / 60000) : null; };
const timeLabel = (minutes: number | null) => minutes == null ? "Sem base" : minutes < 60 ? `${Math.round(minutes)} min` : minutes < 1440 ? `${(minutes / 60).toFixed(1)} h` : `${(minutes / 1440).toFixed(1)} dias`;
const localDate = (value: Date) => `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`;

function Metric({ icon, label, value, hint, tone }: { icon: ReactNode; label: string; value: string | number; hint: string; tone: string }) {
  return <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="flex items-start justify-between"><div><p className="text-[11px] font-black uppercase tracking-wider text-slate-400">{label}</p><strong className="mt-2 block text-2xl font-black text-slate-900 dark:text-white">{value}</strong></div><span className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}>{icon}</span></div><p className="mt-2 text-xs text-slate-500 dark:text-slate-300">{hint}</p></article>;
}
function Bars({ title, data, color = "bg-blue-500" }: { title: string; data: [string, number][]; color?: string }) {
  const max = Math.max(1, ...data.map(([, value]) => value));
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><h3 className="font-black text-slate-900 dark:text-white">{title}</h3><div className="mt-5 space-y-3">{data.length ? data.slice(0, 8).map(([label, value]) => <div key={label}><div className="mb-1 flex justify-between gap-3 text-xs"><span className="truncate font-bold text-slate-600 dark:text-slate-200">{label}</span><b>{value}</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-700"><div className={`h-full rounded-full ${color}`} style={{ width: `${Math.max(3, value / max * 100)}%` }}/></div></div>) : <p className="py-8 text-center text-sm text-slate-400">Sem dados no período.</p>}</div></section>;
}

export function ReportsWorkspace({ chamados, dark, onDownload }: Props) {
  const [period, setPeriod] = useState<Period>("30"); const [start, setStart] = useState(""); const [end, setEnd] = useState("");
  const [responsavel, setResponsavel] = useState(""); const [status, setStatus] = useState(""); const [prioridade, setPrioridade] = useState(""); const [departamento, setDepartamento] = useState("");
  const [teamId, setTeamId] = useState(""); const [municipio, setMunicipio] = useState(""); const [unidade, setUnidade] = useState("");
  const [official, setOfficial] = useState<ReportMetrics | null>(null); const [metricsError, setMetricsError] = useState("");
  const owners = useMemo(() => Array.from(new Set(chamados.map(owner))).sort(), [chamados]);
  const departments = useMemo(() => Array.from(new Set(chamados.map((c) => c.setor || "Não informado"))).sort(), [chamados]);
  const teams = useMemo(() => Array.from(new Map(chamados.filter((c) => c.team_id).map((c) => [String(c.team_id), c.team_name || `Equipe ${c.team_id}`])).entries()), [chamados]);
  const municipalities = useMemo(() => Array.from(new Set(chamados.map((c) => c.municipio_solicitante).filter(Boolean) as string[])).sort(), [chamados]);
  const units = useMemo(() => Array.from(new Set(chamados.filter((c) => !municipio || c.municipio_solicitante === municipio).map((c) => c.unidade_solicitante).filter(Boolean) as string[])).sort(), [chamados, municipio]);
  const range = useMemo(() => { const now = new Date(); now.setHours(23, 59, 59, 999); if (period === "all") return { from: null, to: null }; if (period === "custom") return { from: date(start), to: end ? new Date(`${end}T23:59:59`) : null }; const from = new Date(now); from.setDate(from.getDate() - Number(period) + 1); from.setHours(0, 0, 0, 0); return { from, to: now }; }, [end, period, start]);
  const filtered = useMemo(() => chamados.filter((c) => { const created = date(c.criado_em); return (!range.from || !!created && created >= range.from) && (!range.to || !!created && created <= range.to) && (!responsavel || owner(c) === responsavel) && (!status || c.status === status) && (!prioridade || c.prioridade === prioridade) && (!departamento || (c.setor || "Não informado") === departamento); }), [chamados, departamento, prioridade, range, responsavel, status]);
  const previous = useMemo(() => { if (!range.from || !range.to) return []; const span = range.to.getTime() - range.from.getTime(); const to = new Date(range.from.getTime() - 1); const from = new Date(to.getTime() - span); return chamados.filter((c) => { const created = date(c.criado_em); return created && created >= from && created <= to; }); }, [chamados, range]);
  const closed = filtered.filter((c) => isFinalTicketStatus(c.status)); const open = filtered.filter((c) => !isFinalTicketStatus(c.status));
  const resolutions = closed.map((c) => elapsed(c.criado_em, c.finalizado_em || c.atualizado_em)).filter((v): v is number => v != null);
  const responses = filtered.map((c) => elapsed(c.criado_em, c.primeira_resposta_em || undefined)).filter((v): v is number => v != null);
  const ratings = filtered.map((c) => Number(c.avaliacao_nota || c.avaliacao?.nota)).filter((v) => v > 0);
  const slaBase = closed.filter((c) => c.finalizado_em && c.sla_limite_resolucao); const slaOk = slaBase.filter((c) => new Date(c.finalizado_em!).getTime() <= new Date(c.sla_limite_resolucao!).getTime()).length;
  const change = previous.length ? (filtered.length - previous.length) / previous.length : null;
  const count = (getter: (c: ApiChamado) => string) => Object.entries(filtered.reduce<Record<string, number>>((acc, item) => { const key = getter(item) || "Não informado"; acc[key] = (acc[key] || 0) + 1; return acc; }, {})).sort((a, b) => b[1] - a[1]);
  const exportFilters: FiltrosChamados = { closed: true, ...(range.from ? { data_inicio: localDate(range.from) } : {}), ...(range.to ? { data_fim: localDate(range.to) } : {}), ...(responsavel && responsavel !== "Sem responsável" ? { responsavel } : {}), ...(responsavel === "Sem responsável" ? { sem_responsavel: true } : {}), ...(status ? { status } : {}), ...(prioridade ? { prioridade } : {}), ...(departamento && departamento !== "Não informado" ? { departamento } : {}), ...(teamId ? { team_id: teamId } : {}), ...(municipio ? { municipio } : {}), ...(unidade ? { unidade } : {}) };
  const filterKey = JSON.stringify(exportFilters);
  useEffect(() => {
    let active = true; setMetricsError("");
    obterMetricasRelatorio(JSON.parse(filterKey)).then((result) => { if (active) setOfficial(result); }).catch((error) => { if (active) { setOfficial(null); setMetricsError(error instanceof Error ? error.message : "Erro ao carregar indicadores"); } });
    return () => { active = false; };
  }, [filterKey]);
  const officialBars = (rows: { label: string; total: number }[] | undefined, fallback: [string, number][]) => rows ? rows.map((row) => [row.label, row.total] as [string, number]) : fallback;
  const selectClass = "mt-1 block h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-800";

  return <div className="space-y-5" data-report-theme={dark ? "dark" : "light"}>
    <section className="overflow-hidden rounded-[24px] border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="bg-gradient-to-r from-slate-950 via-slate-900 to-blue-950 px-6 py-6 text-white"><div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-blue-200"><BarChart3 size={15}/>Central de relatórios</p><h2 className="mt-2 text-2xl font-black">Indicadores de atendimento e desempenho</h2><p className="mt-2 text-sm text-slate-300">Visualize os resultados antes de exportar e compare o período atual com o anterior.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => onDownload("pdf", exportFilters)} className="rounded-xl border border-white/15 bg-white/10 px-4 py-2.5 text-sm font-black"><FileText size={16} className="mr-2 inline"/>PDF</button><button onClick={() => onDownload("excel", exportFilters)} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-black"><FileSpreadsheet size={16} className="mr-2 inline"/>Excel</button><button onClick={() => onDownload("csv", exportFilters)} className="rounded-xl border border-white/15 bg-white/10 px-4 py-2.5 text-sm font-black"><Download size={16} className="mr-2 inline"/>CSV</button></div></div></div>
      <div className="grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-4"><label className="text-xs font-black text-slate-500">PERÍODO<select value={period} onChange={(e) => setPeriod(e.target.value as Period)} className={selectClass}><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option><option value="365">Último ano</option><option value="all">Todo o histórico</option><option value="custom">Personalizado</option></select></label>{period === "custom" && <><label className="text-xs font-black text-slate-500">DE<input type="date" value={start} onChange={(e) => setStart(e.target.value)} className={selectClass}/></label><label className="text-xs font-black text-slate-500">ATÉ<input type="date" value={end} onChange={(e) => setEnd(e.target.value)} className={selectClass}/></label></>}<label className="text-xs font-black text-slate-500">TÉCNICO<select value={responsavel} onChange={(e) => setResponsavel(e.target.value)} className={selectClass}><option value="">Todos</option>{owners.map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-xs font-black text-slate-500">EQUIPE<select value={teamId} onChange={(e) => setTeamId(e.target.value)} className={selectClass}><option value="">Todas</option>{teams.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label className="text-xs font-black text-slate-500">MUNICÍPIO<select value={municipio} onChange={(e) => { setMunicipio(e.target.value); setUnidade(""); }} className={selectClass}><option value="">Todos</option>{municipalities.map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-xs font-black text-slate-500">UNIDADE<select value={unidade} onChange={(e) => setUnidade(e.target.value)} className={selectClass}><option value="">Todas</option>{units.map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-xs font-black text-slate-500">STATUS<select value={status} onChange={(e) => setStatus(e.target.value)} className={selectClass}><option value="">Todos</option>{Array.from(new Set(chamados.map((c) => c.status))).sort().map((value) => <option key={value} value={value}>{ticketStatusLabel(value)}</option>)}</select></label><label className="text-xs font-black text-slate-500">PRIORIDADE<select value={prioridade} onChange={(e) => setPrioridade(e.target.value)} className={selectClass}><option value="">Todas</option>{Array.from(new Set(chamados.map((c) => c.prioridade))).sort().map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-xs font-black text-slate-500">DEPARTAMENTO<select value={departamento} onChange={(e) => setDepartamento(e.target.value)} className={selectClass}><option value="">Todos</option>{departments.map((value) => <option key={value}>{value}</option>)}</select></label></div>
    </section>
    {metricsError && <p className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-bold text-amber-800">Indicadores oficiais indisponíveis: {metricsError}. Exibindo cálculo local temporário.</p>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><Metric icon={<CalendarDays size={19}/>} label="Recebidos" value={official?.received ?? filtered.length} hint={change == null ? "Coorte criada no período" : `${change >= 0 ? "+" : ""}${(change * 100).toFixed(1)}% versus período anterior`} tone="bg-blue-50 text-blue-600"/><Metric icon={<CheckCircle2 size={19}/>} label="Concluídos" value={official?.concluded ?? closed.length} hint={`${official?.open ?? open.length} ainda em aberto`} tone="bg-emerald-50 text-emerald-600"/><Metric icon={<Clock3 size={19}/>} label="1ª resposta" value={timeLabel(official?.firstResponseMinutes ?? average(responses))} hint={`${official?.firstResponseBase ?? responses.length} chamado(s) com base`} tone="bg-cyan-50 text-cyan-600"/><Metric icon={<Gauge size={19}/>} label="Resolução" value={timeLabel(official?.resolutionMinutes ?? average(resolutions))} hint={`${official?.resolutionBase ?? resolutions.length} encerrado(s) com datas válidas`} tone="bg-violet-50 text-violet-600"/><Metric icon={<ShieldCheck size={19}/>} label="SLA cumprido" value={(official?.slaRate ?? (slaBase.length ? slaOk / slaBase.length : null)) != null ? `${((official?.slaRate ?? slaOk / slaBase.length) * 100).toFixed(1)}%` : "Sem base"} hint={`${official?.slaBase ?? slaBase.length} chamado(s) com prazo`} tone="bg-amber-50 text-amber-600"/><Metric icon={<Star size={19}/>} label="Satisfação" value={(official?.satisfaction ?? average(ratings)) != null ? `${(official?.satisfaction ?? average(ratings)!).toFixed(1)}/5` : "Sem dados"} hint={`${official?.ratings ?? ratings.length} avaliação(ões)`} tone="bg-yellow-50 text-yellow-600"/></div>
    <div className="grid gap-4 xl:grid-cols-3"><Bars title="Chamados por status" data={officialBars(official?.byStatus, count((c) => ticketStatusLabel(c.status)))}/><Bars title="Chamados por prioridade" data={officialBars(official?.byPriority, count((c) => c.prioridade))} color="bg-amber-500"/><Bars title="Chamados por departamento" data={officialBars(official?.byDepartment, count((c) => c.setor || "Não informado"))} color="bg-cyan-500"/></div>
    <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><Bars title="Volume por técnico" data={officialBars(official?.byTechnician, count(owner))} color="bg-violet-500"/><section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><h3 className="flex items-center gap-2 font-black"><Users size={18}/>Leitura gerencial</h3><div className="mt-4 space-y-3 text-sm text-slate-600 dark:text-slate-200"><p><b>{official?.overdue ?? open.filter((c) => c.vencido).length}</b> chamado(s) aberto(s) com SLA vencido.</p><p><b>{official?.unassigned ?? open.filter((c) => !c.responsavel_id && !c.responsavel).length}</b> chamado(s) aberto(s) sem responsável.</p><p><b>{official?.reopened ?? filtered.filter((c) => c.reaberto_em).length}</b> chamado(s) reaberto(s).</p><p><b>{official?.critical ?? filtered.filter((c) => ["Crítica", "Critica"].includes(c.prioridade)).length}</b> chamado(s) críticos.</p></div></section></div>
  </div>;
}
