import { useCallback, useEffect, useMemo, useState } from "react";
import { BarChart3, CalendarDays, CheckCircle2, Clock3, FolderKanban, GripVertical, Plus, RefreshCw, Search, Sparkles, UserRound, Users } from "lucide-react";
import { toast } from "sonner";
import { atualizarDemandaDesenvolvimento, converterDemandaEmProjeto, listarDemandasDesenvolvimento, listarProjetosDesenvolvimento, moverDemandaDesenvolvimento, obterDashboardDesenvolvimento, type DevelopmentDashboard, type DevelopmentProject, type DevelopmentRequest } from "../../services/api";

const COLUMNS=["nova","em_analise","levantamento_requisitos","avaliacao_tecnica","aguardando_aprovacao","backlog","em_desenvolvimento","em_testes","homologacao","pronto_implantacao","implantacao","concluido","cancelado"];
const label=(value:string)=>value.replaceAll("_"," ").replace(/(^|\s)\S/g,s=>s.toUpperCase());
const tones:Record<string,string>={bug:"bg-orange-100 text-orange-700",melhoria:"bg-blue-100 text-blue-700",automacao:"bg-violet-100 text-violet-700",integracao:"bg-cyan-100 text-cyan-700",dashboard_relatorio:"bg-fuchsia-100 text-fuchsia-700",novo_sistema:"bg-emerald-100 text-emerald-700"};
const priorityTone:Record<string,string>={baixa:"text-slate-600",media:"text-amber-600",alta:"text-orange-600",critica:"text-red-600"};
const columnTones:Record<string,{bar:string;badge:string}>={
  nova:{bar:"bg-sky-500",badge:"bg-sky-100 text-sky-700"},em_analise:{bar:"bg-blue-500",badge:"bg-blue-100 text-blue-700"},levantamento_requisitos:{bar:"bg-indigo-500",badge:"bg-indigo-100 text-indigo-700"},avaliacao_tecnica:{bar:"bg-violet-500",badge:"bg-violet-100 text-violet-700"},aguardando_aprovacao:{bar:"bg-amber-500",badge:"bg-amber-100 text-amber-700"},backlog:{bar:"bg-slate-500",badge:"bg-slate-200 text-slate-700"},em_desenvolvimento:{bar:"bg-fuchsia-500",badge:"bg-fuchsia-100 text-fuchsia-700"},em_testes:{bar:"bg-orange-500",badge:"bg-orange-100 text-orange-700"},homologacao:{bar:"bg-cyan-500",badge:"bg-cyan-100 text-cyan-700"},pronto_implantacao:{bar:"bg-teal-500",badge:"bg-teal-100 text-teal-700"},implantacao:{bar:"bg-emerald-500",badge:"bg-emerald-100 text-emerald-700"},concluido:{bar:"bg-green-600",badge:"bg-green-100 text-green-700"},cancelado:{bar:"bg-rose-500",badge:"bg-rose-100 text-rose-700"}
};

export function DevelopmentWorkspace({dark=false}:{dark?:boolean}){
  const [items,setItems]=useState<DevelopmentRequest[]>([]),[projects,setProjects]=useState<DevelopmentProject[]>([]),[dashboard,setDashboard]=useState<DevelopmentDashboard|null>(null);
  const [loading,setLoading]=useState(true),[query,setQuery]=useState(""),[nature,setNature]=useState(""),[mode,setMode]=useState<"kanban"|"backlog"|"projects">("kanban"),[selected,setSelected]=useState<DevelopmentRequest|null>(null),[drag,setDrag]=useState<number|null>(null);
  const load=useCallback(async()=>{setLoading(true);try{const [requests,summary,projectList]=await Promise.all([listarDemandasDesenvolvimento(),obterDashboardDesenvolvimento(),listarProjetosDesenvolvimento()]);setItems(requests);setDashboard(summary);setProjects(projectList);}catch(e){toast.error(e instanceof Error?e.message:"Erro ao carregar desenvolvimento.");}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const filtered=useMemo(()=>items.filter(item=>(!nature||item.nature===nature)&&(!query||`${item.code} ${item.titulo} ${item.descricao}`.toLowerCase().includes(query.toLowerCase()))),[items,nature,query]);
  async function move(id:number,status:string){const current=items.find(i=>i.id===id);if(!current||current.status===status)return;try{await moverDemandaDesenvolvimento(id,status);setItems(list=>list.map(i=>i.id===id?{...i,status}:i));toast.success(`Demanda movida para ${label(status)}.`);}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível mover.");}}
  const cards=[{label:"Solicitações",value:items.length,icon:Sparkles},{label:"Backlog",value:dashboard?.backlog??0,icon:FolderKanban},{label:"Em desenvolvimento",value:dashboard?.em_desenvolvimento??0,icon:RefreshCw},{label:"Homologação",value:dashboard?.homologacao??0,icon:CheckCircle2},{label:"Concluídas no mês",value:dashboard?.concluidas_mes??0,icon:BarChart3},{label:"Horas economizadas/mês",value:`${dashboard?.horas_economizadas_mes??0}h`,icon:Clock3},{label:"Projetos ativos",value:dashboard?.projetos_ativos??0,icon:Users}];
  return <div className="space-y-4">
    <section className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4 2xl:grid-cols-7">{cards.map(({label:cardLabel,value,icon:Icon},index)=><div key={cardLabel} className={`relative overflow-hidden rounded-xl border px-3 py-3 shadow-sm ${dark?"border-white/10 bg-white/5":"border-slate-200 bg-white"}`}><span className={`absolute inset-x-0 top-0 h-1 ${["bg-sky-500","bg-slate-500","bg-fuchsia-500","bg-cyan-500","bg-emerald-500","bg-amber-500","bg-violet-500"][index]}`}/><div className="flex items-start justify-between gap-2"><span className="text-[10px] font-black uppercase tracking-wide opacity-55">{cardLabel}</span><Icon size={16} className="shrink-0 text-violet-600"/></div><strong className="mt-1 block text-xl leading-none">{value}</strong></div>)}</section>
    <section className={`rounded-2xl border p-3 ${dark?"border-white/10 bg-white/5":"border-slate-200 bg-white"}`}><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><div className="flex rounded-xl bg-slate-100 p-1 dark:bg-slate-800">{(["kanban","backlog","projects"] as const).map(tab=><button key={tab} onClick={()=>setMode(tab)} className={`rounded-lg px-4 py-2 text-sm font-bold ${mode===tab?"bg-white text-violet-700 shadow-sm dark:bg-slate-700":"opacity-60"}`}>{tab==="projects"?"Projetos":label(tab)}</button>)}</div><div className="relative min-w-0 flex-1"><Search size={16} className="absolute left-3 top-3 opacity-40"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por código, título ou descrição" className="h-10 w-full rounded-xl border bg-transparent pl-9 pr-3 text-sm"/></div><select value={nature} onChange={e=>setNature(e.target.value)} className="h-10 rounded-xl border bg-transparent px-3 text-sm"><option value="">Todos os tipos</option>{["bug","melhoria","automacao","integracao","dashboard_relatorio","novo_sistema"].map(v=><option key={v} value={v}>{label(v)}</option>)}</select><button onClick={()=>void load()} className="grid h-10 w-10 place-items-center rounded-xl border" aria-label="Atualizar"><RefreshCw size={16} className={loading?"animate-spin":""}/></button></div></section>
    {loading&&items.length===0?<div className="grid min-h-64 place-items-center"><RefreshCw className="animate-spin text-violet-600"/></div>:mode==="kanban"?<div className="flex snap-x gap-3 overflow-x-auto pb-4">{COLUMNS.map(status=>{const columnItems=filtered.filter(i=>i.status===status),tone=columnTones[status]||columnTones.backlog;return <section key={status} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(drag)void move(drag,status);setDrag(null)}} className={`relative min-h-[410px] w-[300px] shrink-0 snap-start overflow-hidden rounded-2xl border shadow-sm ${dark?"border-white/10 bg-white/5":"border-slate-200 bg-slate-50/80"}`}><div className={`h-1.5 ${tone.bar}`}/><header className="flex min-h-14 items-center justify-between gap-2 border-b px-3"><strong className="text-sm">{label(status)}</strong><span className={`rounded-full px-2.5 py-1 text-xs font-black ${tone.badge}`}>{columnItems.length}</span></header><div className="max-h-[580px] space-y-2 overflow-y-auto p-2.5">{columnItems.map(item=><RequestCard key={item.id} item={item} dark={dark} onClick={()=>setSelected(item)} onDrag={()=>setDrag(item.id)}/>)}{!columnItems.length&&<div className={`grid min-h-28 place-items-center rounded-xl border border-dashed px-5 text-center text-xs ${dark?"border-white/10 text-slate-500":"border-slate-300 text-slate-400"}`}>Arraste uma demanda para esta etapa</div>}</div></section>})}</div>:mode==="backlog"?<Backlog items={filtered} dark={dark} onOpen={setSelected}/>:<Projects projects={projects} dark={dark}/>}
    {selected&&<Detail item={selected} dark={dark} onClose={()=>setSelected(null)} onSaved={async(data)=>{await atualizarDemandaDesenvolvimento(selected.id,data);setSelected(null);await load()}} onConvert={async()=>{await converterDemandaEmProjeto(selected.id);toast.success("Demanda convertida em projeto.");setSelected(null);await load()}}/>}
  </div>
}
function RequestCard({item,dark,onClick,onDrag}:{item:DevelopmentRequest;dark:boolean;onClick:()=>void;onDrag:()=>void}){const priority=item.final_priority||item.calculated_priority;return <button draggable onDragStart={onDrag} onClick={onClick} className={`group w-full cursor-grab rounded-xl border p-3 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-violet-300 hover:shadow-md active:cursor-grabbing ${dark?"border-white/10 bg-slate-900":"border-slate-200 bg-white"}`}><div className="flex items-center justify-between gap-2"><span className="flex items-center gap-1 text-[11px] font-black opacity-55"><GripVertical size={13}/>{item.code}</span><span className={`rounded-full px-2 py-1 text-[9px] font-black uppercase ${tones[item.nature]||"bg-slate-100"}`}>{label(item.nature)}</span></div><strong className="mt-2 line-clamp-2 block text-sm leading-snug">{item.titulo}</strong>{item.problem||item.descricao?<p className="mt-1 line-clamp-2 text-[11px] leading-relaxed opacity-55">{item.problem||item.descricao}</p>:null}<div className="mt-3 flex items-center gap-1.5 text-[11px] opacity-60"><UserRound size={12}/><span className="truncate">{item.developer_name||item.team_name||item.solicitante_nome||"Não atribuído"}</span></div><div className="mt-2 flex items-center justify-between border-t pt-2 text-[11px]"><span className={`font-bold ${priorityTone[priority||""]||"opacity-55"}`}>{priority?label(priority):"Sem prioridade"}</span><span className="flex items-center gap-1 font-bold opacity-60"><CalendarDays size={12}/>{new Date(item.created_at).toLocaleDateString("pt-BR")}</span></div></button>}
function Backlog({items,dark,onOpen}:{items:DevelopmentRequest[];dark:boolean;onOpen:(i:DevelopmentRequest)=>void}){return <div className={`overflow-x-auto rounded-2xl border ${dark?"border-white/10":"border-slate-200 bg-white"}`}><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left text-xs uppercase opacity-55">{["ID","Título","Tipo","Setor","Prioridade","Pontuação","Responsável","Esforço","Status","Data"].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{items.map(i=><tr key={i.id} onClick={()=>onOpen(i)} className="cursor-pointer border-b last:border-0 hover:bg-violet-500/5"><td className="p-3 font-bold">{i.code}</td><td className="p-3">{i.titulo}</td><td className="p-3">{label(i.nature)}</td><td className="p-3">{i.sectors?.join(", ")||"—"}</td><td className="p-3">{label(i.final_priority||i.calculated_priority||"—")}</td><td className="p-3">{i.score?`${i.score}/20`:"—"}</td><td className="p-3">{i.developer_name||i.team_name||"Não atribuído"}</td><td className="p-3">{i.effort?label(i.effort):"—"}</td><td className="p-3">{label(i.status)}</td><td className="p-3">{new Date(i.created_at).toLocaleDateString("pt-BR")}</td></tr>)}</tbody></table>{!items.length&&<div className="p-12 text-center opacity-50">Nenhuma demanda encontrada.</div>}</div>}
function Projects({projects,dark}:{projects:DevelopmentProject[];dark:boolean}){return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.map(p=><article key={p.id} className={`rounded-2xl border p-5 ${dark?"border-white/10 bg-white/5":"border-slate-200 bg-white"}`}><div className="flex justify-between"><span className="text-xs font-black text-violet-600">{p.code}</span><span className="text-xs font-bold">{label(p.status)}</span></div><h3 className="mt-2 font-black">{p.name}</h3><p className="mt-2 line-clamp-2 text-sm opacity-60">{p.description||"Sem descrição"}</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-violet-600" style={{width:`${p.progress}%`}}/></div><div className="mt-2 flex justify-between text-xs"><span>{p.task_count||0} tarefas</span><b>{p.progress}%</b></div></article>)}{!projects.length&&<div className="col-span-full p-12 text-center opacity-50">Nenhum projeto cadastrado.</div>}</div>}
function Detail({item,dark,onClose,onSaved,onConvert}:{item:DevelopmentRequest;dark:boolean;onClose:()=>void;onSaved:(data:Record<string,unknown>)=>Promise<void>;onConvert:()=>Promise<void>}){const [scores,setScores]=useState({impact:item.impact||3,reach:item.reach||3,gain:item.gain||3,urgency:item.urgency||3}),[saving,setSaving]=useState(false);async function save(){setSaving(true);try{await onSaved(scores);toast.success("Avaliação salva.")}catch(e){toast.error(e instanceof Error?e.message:"Erro ao salvar.")}finally{setSaving(false)}}return <div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/50 p-3" onMouseDown={onClose}><div onMouseDown={e=>e.stopPropagation()} className={`max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded-3xl border p-6 shadow-2xl ${dark?"border-white/10 bg-slate-900":"border-slate-200 bg-white"}`}><div className="flex justify-between gap-3"><div><span className="text-sm font-black text-violet-600">{item.code}</span><h2 className="text-xl font-black">{item.titulo}</h2></div><button onClick={onClose} className="h-10 rounded-xl border px-4">Fechar</button></div><p className="mt-4 text-sm opacity-70">{item.problem||item.descricao}</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{Object.entries(scores).map(([key,value])=><label key={key} className="rounded-xl border p-3 text-sm font-bold">{label(key)}: {value}/5<input className="mt-2 w-full" type="range" min="1" max="5" value={value} onChange={e=>setScores({...scores,[key]:Number(e.target.value)})}/></label>)}</div><div className="mt-5 rounded-xl bg-violet-50 p-4 text-sm text-violet-900"><b>Economia estimada:</b> {item.savings?.horas_mes||0}h/mês · {item.savings?.horas_ano||0}h/ano</div><div className="mt-6 flex flex-col gap-2 sm:flex-row sm:justify-end"><button onClick={()=>void onConvert()} disabled={Boolean(item.converted_project_id)} className="h-11 rounded-xl border px-4 font-bold disabled:opacity-40"><Plus size={16} className="mr-2 inline"/>{item.converted_project_id?"Projeto já criado":"Converter em projeto"}</button><button onClick={()=>void save()} disabled={saving} className="h-11 rounded-xl bg-violet-600 px-5 font-bold text-white disabled:opacity-50">{saving?"Salvando…":"Salvar avaliação"}</button></div></div></div>}
