import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertCircle, BarChart3, CheckCircle2, Clock3, FolderKanban, Plus, RefreshCw, Search, Sparkles, Users } from "lucide-react";
import { toast } from "sonner";
import { atualizarDemandaDesenvolvimento, converterDemandaEmProjeto, listarDemandasDesenvolvimento, listarProjetosDesenvolvimento, moverDemandaDesenvolvimento, obterDashboardDesenvolvimento, type DevelopmentDashboard, type DevelopmentProject, type DevelopmentRequest } from "../../services/api";

const COLUMNS=["nova","em_analise","levantamento_requisitos","avaliacao_tecnica","aguardando_aprovacao","backlog","em_desenvolvimento","em_testes","homologacao","pronto_implantacao","implantacao","concluido","cancelado"];
const label=(value:string)=>value.replaceAll("_"," ").replace(/(^|\s)\S/g,s=>s.toUpperCase());
const tones:Record<string,string>={bug:"bg-orange-100 text-orange-700",melhoria:"bg-blue-100 text-blue-700",automacao:"bg-violet-100 text-violet-700",integracao:"bg-cyan-100 text-cyan-700",dashboard_relatorio:"bg-fuchsia-100 text-fuchsia-700",novo_sistema:"bg-emerald-100 text-emerald-700"};
const priorityTone:Record<string,string>={baixa:"text-slate-600",media:"text-amber-600",alta:"text-orange-600",critica:"text-red-600"};

export function DevelopmentWorkspace({dark=false}:{dark?:boolean}){
  const [items,setItems]=useState<DevelopmentRequest[]>([]),[projects,setProjects]=useState<DevelopmentProject[]>([]),[dashboard,setDashboard]=useState<DevelopmentDashboard|null>(null);
  const [loading,setLoading]=useState(true),[query,setQuery]=useState(""),[nature,setNature]=useState(""),[mode,setMode]=useState<"kanban"|"backlog"|"projects">("kanban"),[selected,setSelected]=useState<DevelopmentRequest|null>(null),[drag,setDrag]=useState<number|null>(null);
  const load=useCallback(async()=>{setLoading(true);try{const [requests,summary,projectList]=await Promise.all([listarDemandasDesenvolvimento(),obterDashboardDesenvolvimento(),listarProjetosDesenvolvimento()]);setItems(requests);setDashboard(summary);setProjects(projectList);}catch(e){toast.error(e instanceof Error?e.message:"Erro ao carregar desenvolvimento.");}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const filtered=useMemo(()=>items.filter(item=>(!nature||item.nature===nature)&&(!query||`${item.code} ${item.titulo} ${item.descricao}`.toLowerCase().includes(query.toLowerCase()))),[items,nature,query]);
  async function move(id:number,status:string){const current=items.find(i=>i.id===id);if(!current||current.status===status)return;try{await moverDemandaDesenvolvimento(id,status);setItems(list=>list.map(i=>i.id===id?{...i,status}:i));toast.success(`Demanda movida para ${label(status)}.`);}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível mover.");}}
  const cards=[{label:"Solicitações",value:items.length,icon:Sparkles},{label:"Backlog",value:dashboard?.backlog??0,icon:FolderKanban},{label:"Em desenvolvimento",value:dashboard?.em_desenvolvimento??0,icon:RefreshCw},{label:"Homologação",value:dashboard?.homologacao??0,icon:CheckCircle2},{label:"Concluídas no mês",value:dashboard?.concluidas_mes??0,icon:BarChart3},{label:"Horas economizadas/mês",value:`${dashboard?.horas_economizadas_mes??0}h`,icon:Clock3},{label:"Projetos ativos",value:dashboard?.projetos_ativos??0,icon:Users}];
  return <div className="space-y-5">
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({label:cardLabel,value,icon:Icon})=><div key={cardLabel} className={`rounded-2xl border p-4 ${dark?"border-white/10 bg-white/5":"border-slate-200 bg-white"}`}><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-wide opacity-55">{cardLabel}</span><Icon size={18} className="text-violet-600"/></div><strong className="mt-2 block text-2xl">{value}</strong></div>)}</section>
    <section className={`rounded-2xl border p-3 ${dark?"border-white/10 bg-white/5":"border-slate-200 bg-white"}`}><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><div className="flex rounded-xl bg-slate-100 p-1 dark:bg-slate-800">{(["kanban","backlog","projects"] as const).map(tab=><button key={tab} onClick={()=>setMode(tab)} className={`rounded-lg px-4 py-2 text-sm font-bold ${mode===tab?"bg-white text-violet-700 shadow-sm dark:bg-slate-700":"opacity-60"}`}>{tab==="projects"?"Projetos":label(tab)}</button>)}</div><div className="relative min-w-0 flex-1"><Search size={16} className="absolute left-3 top-3 opacity-40"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por código, título ou descrição" className="h-10 w-full rounded-xl border bg-transparent pl-9 pr-3 text-sm"/></div><select value={nature} onChange={e=>setNature(e.target.value)} className="h-10 rounded-xl border bg-transparent px-3 text-sm"><option value="">Todos os tipos</option>{["bug","melhoria","automacao","integracao","dashboard_relatorio","novo_sistema"].map(v=><option key={v} value={v}>{label(v)}</option>)}</select><button onClick={()=>void load()} className="grid h-10 w-10 place-items-center rounded-xl border" aria-label="Atualizar"><RefreshCw size={16} className={loading?"animate-spin":""}/></button></div></section>
    {loading&&items.length===0?<div className="grid min-h-64 place-items-center"><RefreshCw className="animate-spin text-violet-600"/></div>:mode==="kanban"?<div className="flex gap-3 overflow-x-auto pb-4">{COLUMNS.map(status=><section key={status} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(drag)void move(drag,status);setDrag(null)}} className={`min-h-72 w-72 shrink-0 rounded-2xl border p-3 ${dark?"border-white/10 bg-white/5":"border-slate-200 bg-slate-50"}`}><header className="mb-3 flex items-center justify-between"><strong className="text-sm">{label(status)}</strong><span className="rounded-full bg-slate-200 px-2 py-0.5 text-xs text-slate-700">{filtered.filter(i=>i.status===status).length}</span></header><div className="space-y-2">{filtered.filter(i=>i.status===status).map(item=><RequestCard key={item.id} item={item} dark={dark} onClick={()=>setSelected(item)} onDrag={()=>setDrag(item.id)}/>)}</div></section>)}</div>:mode==="backlog"?<Backlog items={filtered} dark={dark} onOpen={setSelected}/>:<Projects projects={projects} dark={dark}/>} 
    {selected&&<Detail item={selected} dark={dark} onClose={()=>setSelected(null)} onSaved={async(data)=>{await atualizarDemandaDesenvolvimento(selected.id,data);setSelected(null);await load()}} onConvert={async()=>{await converterDemandaEmProjeto(selected.id);toast.success("Demanda convertida em projeto.");setSelected(null);await load()}}/>}
  </div>
}
function RequestCard({item,dark,onClick,onDrag}:{item:DevelopmentRequest;dark:boolean;onClick:()=>void;onDrag:()=>void}){const priority=item.final_priority||item.calculated_priority;return <button draggable onDragStart={onDrag} onClick={onClick} className={`w-full rounded-xl border p-3 text-left shadow-sm transition hover:-translate-y-0.5 ${dark?"border-white/10 bg-slate-900":"border-slate-200 bg-white"}`}><div className="flex items-center justify-between gap-2"><span className="text-xs font-black opacity-50">{item.code}</span><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${tones[item.nature]||"bg-slate-100"}`}>{label(item.nature)}</span></div><strong className="mt-2 line-clamp-2 block text-sm">{item.titulo}</strong><div className="mt-3 flex items-center justify-between text-xs"><span className={priorityTone[priority||""]}>{priority?label(priority):"Sem pontuação"}</span><span className="font-bold">{item.score?`${item.score}/20`:"—"}</span></div></button>}
function Backlog({items,dark,onOpen}:{items:DevelopmentRequest[];dark:boolean;onOpen:(i:DevelopmentRequest)=>void}){return <div className={`overflow-x-auto rounded-2xl border ${dark?"border-white/10":"border-slate-200 bg-white"}`}><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left text-xs uppercase opacity-55">{["ID","Título","Tipo","Setor","Prioridade","Pontuação","Responsável","Esforço","Status","Data"].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{items.map(i=><tr key={i.id} onClick={()=>onOpen(i)} className="cursor-pointer border-b last:border-0 hover:bg-violet-500/5"><td className="p-3 font-bold">{i.code}</td><td className="p-3">{i.titulo}</td><td className="p-3">{label(i.nature)}</td><td className="p-3">{i.sectors?.join(", ")||"—"}</td><td className="p-3">{label(i.final_priority||i.calculated_priority||"—")}</td><td className="p-3">{i.score?`${i.score}/20`:"—"}</td><td className="p-3">{i.developer_name||i.team_name||"Não atribuído"}</td><td className="p-3">{i.effort?label(i.effort):"—"}</td><td className="p-3">{label(i.status)}</td><td className="p-3">{new Date(i.created_at).toLocaleDateString("pt-BR")}</td></tr>)}</tbody></table>{!items.length&&<div className="p-12 text-center opacity-50">Nenhuma demanda encontrada.</div>}</div>}
function Projects({projects,dark}:{projects:DevelopmentProject[];dark:boolean}){return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.map(p=><article key={p.id} className={`rounded-2xl border p-5 ${dark?"border-white/10 bg-white/5":"border-slate-200 bg-white"}`}><div className="flex justify-between"><span className="text-xs font-black text-violet-600">{p.code}</span><span className="text-xs font-bold">{label(p.status)}</span></div><h3 className="mt-2 font-black">{p.name}</h3><p className="mt-2 line-clamp-2 text-sm opacity-60">{p.description||"Sem descrição"}</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-violet-600" style={{width:`${p.progress}%`}}/></div><div className="mt-2 flex justify-between text-xs"><span>{p.task_count||0} tarefas</span><b>{p.progress}%</b></div></article>)}{!projects.length&&<div className="col-span-full p-12 text-center opacity-50">Nenhum projeto cadastrado.</div>}</div>}
function Detail({item,dark,onClose,onSaved,onConvert}:{item:DevelopmentRequest;dark:boolean;onClose:()=>void;onSaved:(data:Record<string,unknown>)=>Promise<void>;onConvert:()=>Promise<void>}){const [scores,setScores]=useState({impact:item.impact||3,reach:item.reach||3,gain:item.gain||3,urgency:item.urgency||3}),[saving,setSaving]=useState(false);async function save(){setSaving(true);try{await onSaved(scores);toast.success("Avaliação salva.")}catch(e){toast.error(e instanceof Error?e.message:"Erro ao salvar.")}finally{setSaving(false)}}return <div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/50 p-3" onMouseDown={onClose}><div onMouseDown={e=>e.stopPropagation()} className={`max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded-3xl border p-6 shadow-2xl ${dark?"border-white/10 bg-slate-900":"border-slate-200 bg-white"}`}><div className="flex justify-between gap-3"><div><span className="text-sm font-black text-violet-600">{item.code}</span><h2 className="text-xl font-black">{item.titulo}</h2></div><button onClick={onClose} className="h-10 rounded-xl border px-4">Fechar</button></div><p className="mt-4 text-sm opacity-70">{item.problem||item.descricao}</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{Object.entries(scores).map(([key,value])=><label key={key} className="rounded-xl border p-3 text-sm font-bold">{label(key)}: {value}/5<input className="mt-2 w-full" type="range" min="1" max="5" value={value} onChange={e=>setScores({...scores,[key]:Number(e.target.value)})}/></label>)}</div><div className="mt-5 rounded-xl bg-violet-50 p-4 text-sm text-violet-900"><b>Economia estimada:</b> {item.savings?.horas_mes||0}h/mês · {item.savings?.horas_ano||0}h/ano</div><div className="mt-6 flex flex-col gap-2 sm:flex-row sm:justify-end"><button onClick={()=>void onConvert()} disabled={Boolean(item.converted_project_id)} className="h-11 rounded-xl border px-4 font-bold disabled:opacity-40"><Plus size={16} className="mr-2 inline"/>{item.converted_project_id?"Projeto já criado":"Converter em projeto"}</button><button onClick={()=>void save()} disabled={saving} className="h-11 rounded-xl bg-violet-600 px-5 font-bold text-white disabled:opacity-50">{saving?"Salvando…":"Salvar avaliação"}</button></div></div></div>}
