const pool = require("../config/database");
const { scoreDevelopment, calculateSavings, DEVELOPMENT_TYPES, DEVELOPMENT_STATUSES, PROJECT_STATUSES, TASK_STATUSES, EFFORTS } = require("../domain/development");
const { ehUsuarioComum } = require("../utils/permissoes");
const { recordError } = require("../services/systemDiagnosticsService");

const allowedRequestFields = ["nature","current_process","problem","expected_result","frequency","executions_per_month","people_involved","current_time_minutes","automated_time_minutes","sectors","systems","no_delivery_impact","expected_benefits","impact","reach","gain","urgency","final_priority","priority_reason","effort","story_points","feasibility","developer_id","team_id","due_date","rejection_reason","rejection_details"];
const clean = (body, allowed) => Object.fromEntries(allowed.filter((key) => body[key] !== undefined).map((key) => [key, body[key] === "" ? null : body[key]]));
const placeholders = (obj, start = 1) => Object.keys(obj).map((key, index) => `${key}=$${index + start}`).join(", ");
const httpError = (status, message) => Object.assign(new Error(message), { status });
function handle(res, error, req) { if(!error.status)recordError({source:"development",message:error.message,requestId:req.id,path:req.originalUrl}); res.status(error.status || 500).json({ erro: error.status ? error.message : "Erro interno no fluxo de desenvolvimento.", requestId: req.id }); }
function notify(client, userId, title, message, link, type = "info") { if (!userId) return Promise.resolve(); return client.query("INSERT INTO notificacoes(usuario_id,titulo,mensagem,tipo,link) VALUES($1,$2,$3,$4,$5)", [userId,title,message,type,link]); }
async function notifyInTransaction(client,userId,title,message,link,type="info"){if(!userId)return;await client.query("SAVEPOINT development_notification");try{await notify(client,userId,title,message,link,type);await client.query("RELEASE SAVEPOINT development_notification");}catch(error){await client.query("ROLLBACK TO SAVEPOINT development_notification");await client.query("RELEASE SAVEPOINT development_notification");recordError({source:"development_notification",message:error.message,path:link});}}
function audit(client, requestId, actorId, event, previous, next, comment, internal = false) { return client.query("INSERT INTO development_history(request_id,actor_id,event_type,previous_value,new_value,comment,internal) VALUES($1,$2,$3,$4,$5,$6,$7)", [requestId,actorId,event,previous ? JSON.stringify(previous) : null,next ? JSON.stringify(next) : null,comment || null,internal]); }

async function requestAccess(id, user, client = pool) {
  const result = await client.query(`SELECT d.*, c.titulo, c.descricao, c.usuario_id AS requester_id, c.solicitante AS solicitante_nome, c.email_solicitante AS solicitante_email, u.nome developer_name, t.name team_name
    FROM development_requests d JOIN chamados c ON c.id=d.ticket_id LEFT JOIN usuarios u ON u.id=d.developer_id LEFT JOIN teams t ON t.id=d.team_id WHERE d.id=$1 OR d.code=$2`, [Number(id) || 0, String(id)]);
  const item = result.rows[0];
  if (!item) throw httpError(404, "Demanda não encontrada.");
  if (ehUsuarioComum(user.perfil) && Number(item.requester_id) !== Number(user.id)) throw httpError(403, "Você não pode acessar esta demanda.");
  return item;
}

async function listRequests(req, res) { try {
  const values=[]; const where=[]; const add=(sql,value)=>{values.push(value);where.push(sql.replace("?",`$${values.length}`));};
  if (ehUsuarioComum(req.user.perfil)) add("c.usuario_id=?",req.user.id);
  for (const [key,column] of Object.entries({status:"d.status",nature:"d.nature",priority:"COALESCE(d.final_priority,d.calculated_priority)",developer_id:"d.developer_id",team_id:"d.team_id"})) if(req.query[key]) add(`${column}=?`,req.query[key]);
  if(req.query.q){values.push(`%${String(req.query.q).slice(0,120)}%`);where.push(`(d.code ILIKE $${values.length} OR c.titulo ILIKE $${values.length} OR c.descricao ILIKE $${values.length})`);}
  const result=await pool.query(`SELECT d.*,c.titulo,c.descricao,c.usuario_id requester_id,c.solicitante AS solicitante_nome,c.email_solicitante AS solicitante_email,u.nome developer_name,t.name team_name FROM development_requests d JOIN chamados c ON c.id=d.ticket_id LEFT JOIN usuarios u ON u.id=d.developer_id LEFT JOIN teams t ON t.id=d.team_id ${where.length?`WHERE ${where.join(" AND ")}`:""} ORDER BY COALESCE(d.score,0) DESC,d.created_at DESC LIMIT 500`,values);
  res.json(result.rows.map(item=>({...item,savings:calculateSavings({tempo_antes_minutos:item.current_time_minutes,tempo_depois_minutos:item.automated_time_minutes,execucoes_mes:item.executions_per_month,pessoas:item.people_involved})})));
} catch(error){handle(res,error,req);} }

async function getRequest(req,res){try{const item=await requestAccess(req.params.id,req.user);const [history,approvals,deployments,relations]=await Promise.all([
  pool.query(`SELECT h.*,u.nome actor_name FROM development_history h LEFT JOIN usuarios u ON u.id=h.actor_id WHERE request_id=$1 ${ehUsuarioComum(req.user.perfil)?"AND internal=FALSE":""} ORDER BY created_at`,[item.id]),
  pool.query("SELECT a.*,u.nome decided_by_name FROM development_approvals a LEFT JOIN usuarios u ON u.id=a.decided_by WHERE request_id=$1 ORDER BY created_at",[item.id]),
  pool.query("SELECT d.*,u.nome responsible_name FROM development_deployments d LEFT JOIN usuarios u ON u.id=d.responsible_id WHERE request_id=$1 ORDER BY deployed_at DESC",[item.id]),
  pool.query("SELECT r.* FROM ticket_relations r WHERE source_ticket_id=$1 ORDER BY created_at DESC",[item.ticket_id])]);
  res.json({...item,history:history.rows,approvals:approvals.rows,deployments:deployments.rows,relations:relations.rows,savings:calculateSavings({tempo_antes_minutos:item.current_time_minutes,tempo_depois_minutos:item.automated_time_minutes,execucoes_mes:item.executions_per_month,pessoas:item.people_involved})});
}catch(error){handle(res,error,req);}}

async function createRequest(req,res){const client=await pool.connect();try{await client.query("BEGIN");const ticket=await client.query("SELECT id,usuario_id,titulo FROM chamados WHERE id=$1",[req.body.ticket_id]);if(!ticket.rows[0])throw httpError(404,"Chamado não encontrado.");if(ehUsuarioComum(req.user.perfil)&&Number(ticket.rows[0].usuario_id)!==Number(req.user.id))throw httpError(403,"Chamado pertence a outro solicitante.");if(!DEVELOPMENT_TYPES.includes(req.body.nature))throw httpError(400,"Natureza de desenvolvimento inválida.");if(req.body.nature!=="bug"&&!String(req.body.current_process||"").trim())throw httpError(400,"Explique como o processo funciona atualmente.");const data=clean(req.body,allowedRequestFields);data.ticket_id=ticket.rows[0].id;data.created_by=req.user.id;const keys=Object.keys(data);const result=await client.query(`INSERT INTO development_requests(${keys.join(",")}) VALUES(${keys.map((_,i)=>`$${i+1}`).join(",")}) RETURNING *`,Object.values(data));await audit(client,result.rows[0].id,req.user.id,"criacao",null,{status:"nova",nature:data.nature},req.body.comment);await notifyInTransaction(client,ticket.rows[0].usuario_id,"Demanda recebida",`${ticket.rows[0].titulo} foi registrada para análise.`,`/admin?tab=desenvolvimento&id=${result.rows[0].id}`,"success");await client.query("COMMIT");res.status(201).json(result.rows[0]);}catch(error){await client.query("ROLLBACK");handle(res,error,req);}finally{client.release();}}

async function updateRequest(req,res){const client=await pool.connect();try{await client.query("BEGIN");const previous=await requestAccess(req.params.id,req.user,client);if(ehUsuarioComum(req.user.perfil))throw httpError(403,"A análise é restrita à equipe de TI.");const data=clean(req.body,allowedRequestFields);if([data.impact,data.reach,data.gain,data.urgency].every(v=>v!=null)){const calculated=scoreDevelopment({impacto:data.impact,alcance:data.reach,ganho:data.gain,urgencia:data.urgency});data.score=calculated.total;data.calculated_priority=calculated.prioridade;}if(!Object.keys(data).length)throw httpError(400,"Nenhum campo válido informado.");const values=Object.values(data);values.push(previous.id);const result=await client.query(`UPDATE development_requests SET ${placeholders(data)},updated_at=NOW() WHERE id=$${values.length} RETURNING *`,values);await audit(client,previous.id,req.user.id,"edicao",previous,result.rows[0],req.body.comment,Boolean(req.body.internal));if(data.developer_id&&Number(data.developer_id)!==Number(previous.developer_id))await notifyInTransaction(client,data.developer_id,"Nova demanda atribuída",`${previous.code} foi atribuída a você.`,`/admin?tab=desenvolvimento&id=${previous.id}`);await client.query("COMMIT");res.json(result.rows[0]);}catch(error){await client.query("ROLLBACK");handle(res,error,req);}finally{client.release();}}

async function changeStatus(req,res){const client=await pool.connect();let notification=null;try{await client.query("BEGIN");const previous=await requestAccess(req.params.id,req.user,client);if(ehUsuarioComum(req.user.perfil))throw httpError(403,"Mudança de status restrita à equipe de TI.");const status=String(req.body.status||"");if(!DEVELOPMENT_STATUSES.includes(status))throw httpError(400,"Status inválido.");if(status==="cancelado"&&!String(req.body.comment||"").trim())throw httpError(400,"Informe o motivo do cancelamento.");const result=await client.query("UPDATE development_requests SET status=$1,updated_at=NOW(),completed_at=CASE WHEN $1='concluido' THEN NOW() ELSE completed_at END WHERE id=$2 RETURNING *",[status,previous.id]);await audit(client,previous.id,req.user.id,"mudanca_status",{status:previous.status},{status},req.body.comment);notification={userId:previous.requester_id,title:"Demanda atualizada",message:`${previous.code} agora está em ${status.replaceAll("_"," ")}.`,link:`/minhas-solicitacoes?id=${previous.id}`};await client.query("COMMIT");res.json(result.rows[0]);}catch(error){await client.query("ROLLBACK");return handle(res,error,req);}finally{client.release();}if(notification)notify(pool,notification.userId,notification.title,notification.message,notification.link).catch(error=>recordError({source:"development_notification",message:error.message,requestId:req.id,path:req.originalUrl}));}

async function decide(req,res){const client=await pool.connect();try{await client.query("BEGIN");const item=await requestAccess(req.params.id,req.user,client);const kind=String(req.body.kind);const decision=String(req.body.decision);if(!["aprovacao","homologacao"].includes(kind)||!["aprovado","reprovado","ajustes"].includes(decision))throw httpError(400,"Decisão inválida.");if(kind==="aprovacao"&&ehUsuarioComum(req.user.perfil))throw httpError(403,"Aprovação restrita aos responsáveis pela análise.");if((decision==="ajustes"||decision==="reprovado")&&!String(req.body.comment||"").trim())throw httpError(400,"Comentário obrigatório para ajustes ou reprovação.");if(kind==="homologacao"&&ehUsuarioComum(req.user.perfil)&&Number(item.requester_id)!==Number(req.user.id))throw httpError(403,"Somente o solicitante pode homologar esta demanda.");const approval=await client.query("INSERT INTO development_approvals(request_id,kind,decision,comment,decided_by) VALUES($1,$2,$3,$4,$5) RETURNING *",[item.id,kind,decision,req.body.comment||null,req.user.id]);const status=kind==="homologacao"?(decision==="aprovado"?"pronto_implantacao":decision==="ajustes"?"em_desenvolvimento":"homologacao"):(decision==="aprovado"?"backlog":"cancelado");await client.query("UPDATE development_requests SET status=$1,updated_at=NOW() WHERE id=$2",[status,item.id]);await audit(client,item.id,req.user.id,kind,{status:item.status},{decision,status},req.body.comment);await notifyInTransaction(client,item.developer_id,`Resultado de ${kind}`,`${item.code}: ${decision}.`,`/admin?tab=desenvolvimento&id=${item.id}`,decision==="aprovado"?"success":"warning");await client.query("COMMIT");res.status(201).json(approval.rows[0]);}catch(error){await client.query("ROLLBACK");handle(res,error,req);}finally{client.release();}}

async function deploy(req,res){const client=await pool.connect();try{await client.query("BEGIN");const item=await requestAccess(req.params.id,req.user,client);if(ehUsuarioComum(req.user.perfil))throw httpError(403,"Implantação restrita à equipe de TI.");const environment=String(req.body.environment||"");if(!["desenvolvimento","homologacao","producao"].includes(environment))throw httpError(400,"Ambiente inválido.");const result=await client.query("INSERT INTO development_deployments(request_id,environment,version,notes,system_url,responsible_id,deployed_at) VALUES($1,$2,$3,$4,$5,$6,COALESCE($7,NOW())) RETURNING *",[item.id,environment,req.body.version||null,req.body.notes||null,req.body.system_url||null,req.user.id,req.body.deployed_at||null]);await client.query("UPDATE development_requests SET status='implantacao',updated_at=NOW() WHERE id=$1",[item.id]);await audit(client,item.id,req.user.id,"implantacao",{status:item.status},{environment,version:req.body.version,status:"implantacao"},req.body.notes);await notifyInTransaction(client,item.requester_id,"Demanda implantada",`${item.code} foi implantada em ${environment}.`,`/minhas-solicitacoes?id=${item.id}`,"success");await client.query("COMMIT");res.status(201).json(result.rows[0]);}catch(error){await client.query("ROLLBACK");handle(res,error,req);}finally{client.release();}}

async function convertProject(req,res){const client=await pool.connect();try{await client.query("BEGIN");const item=await requestAccess(req.params.id,req.user,client);if(ehUsuarioComum(req.user.perfil))throw httpError(403,"Conversão restrita à equipe de TI.");if(item.converted_project_id)throw httpError(409,"Demanda já convertida em projeto.");const project=await client.query("INSERT INTO development_projects(name,description,requester_id,sponsor_id,developer_id,team_id,priority,status,planned_start,planned_delivery,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,'planejamento',$8,$9,$10,$11) RETURNING *",[req.body.name||item.titulo,req.body.description||item.expected_result||item.descricao,item.requester_id,req.body.sponsor_id||null,item.developer_id,item.team_id,item.final_priority||item.calculated_priority,req.body.planned_start||null,req.body.planned_delivery||null,req.body.notes||null,req.user.id]);await client.query("UPDATE development_requests SET converted_project_id=$1,updated_at=NOW() WHERE id=$2",[project.rows[0].id,item.id]);await client.query("INSERT INTO ticket_relations(source_ticket_id,target_project_id,relation_type,created_by) VALUES($1,$2,'convertido_projeto',$3)",[item.ticket_id,project.rows[0].id,req.user.id]);await audit(client,item.id,req.user.id,"conversao_projeto",null,{project_id:project.rows[0].id,code:project.rows[0].code},req.body.comment);await notifyInTransaction(client,item.requester_id,"Demanda convertida em projeto",`${item.code} tornou-se ${project.rows[0].code}.`,`/admin?tab=projetos&id=${project.rows[0].id}`,"success");await client.query("COMMIT");res.status(201).json(project.rows[0]);}catch(error){await client.query("ROLLBACK");handle(res,error,req);}finally{client.release();}}

async function listProjects(req,res){try{const values=[];let where="";if(ehUsuarioComum(req.user.perfil)){values.push(req.user.id);where="WHERE p.requester_id=$1 OR p.sponsor_id=$1";}const result=await pool.query(`SELECT p.*,u.nome developer_name,t.name team_name,(SELECT COUNT(*) FROM project_tasks pt WHERE pt.project_id=p.id) task_count FROM development_projects p LEFT JOIN usuarios u ON u.id=p.developer_id LEFT JOIN teams t ON t.id=p.team_id ${where} ORDER BY p.updated_at DESC`,values);res.json(result.rows);}catch(error){handle(res,error,req);}}
async function getProject(req,res){try{const result=await pool.query("SELECT * FROM development_projects WHERE id=$1 OR code=$2",[Number(req.params.id)||0,String(req.params.id)]);const item=result.rows[0];if(!item)throw httpError(404,"Projeto não encontrado.");if(ehUsuarioComum(req.user.perfil)&&![item.requester_id,item.sponsor_id].map(Number).includes(Number(req.user.id)))throw httpError(403,"Acesso negado.");const tasks=await pool.query("SELECT pt.*,u.nome responsible_name FROM project_tasks pt LEFT JOIN usuarios u ON u.id=pt.responsible_id WHERE project_id=$1 ORDER BY created_at",[item.id]);res.json({...item,tasks:tasks.rows});}catch(error){handle(res,error,req);}}
async function createProject(req,res){try{if(ehUsuarioComum(req.user.perfil))throw httpError(403,"Criação de projetos restrita à equipe de TI.");if(!String(req.body.name||"").trim())throw httpError(400,"Nome obrigatório.");const fields=clean(req.body,["name","description","requester_id","sponsor_id","developer_id","team_id","priority","status","progress","planned_start","planned_delivery","notes"]);fields.name=req.body.name;fields.created_by=req.user.id;if(fields.status&&!PROJECT_STATUSES.includes(fields.status))throw httpError(400,"Status inválido.");const keys=Object.keys(fields);const result=await pool.query(`INSERT INTO development_projects(${keys.join(",")}) VALUES(${keys.map((_,i)=>`$${i+1}`).join(",")}) RETURNING *`,Object.values(fields));res.status(201).json(result.rows[0]);}catch(error){handle(res,error,req);}}
async function addTask(req,res){try{if(ehUsuarioComum(req.user.perfil))throw httpError(403,"Tarefas são internas da equipe de TI.");if(!String(req.body.title||"").trim())throw httpError(400,"Título obrigatório.");if(req.body.status&&!TASK_STATUSES.includes(req.body.status))throw httpError(400,"Status inválido.");if(req.body.effort&&!EFFORTS.includes(req.body.effort))throw httpError(400,"Esforço inválido.");const result=await pool.query("INSERT INTO project_tasks(project_id,title,description,responsible_id,priority,status,due_date,effort,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *",[req.params.id,req.body.title,req.body.description||null,req.body.responsible_id||null,req.body.priority||null,req.body.status||"a_fazer",req.body.due_date||null,req.body.effort||null,req.user.id]);res.status(201).json(result.rows[0]);}catch(error){handle(res,error,req);}}
async function dashboard(req,res){try{const result=await pool.query(`SELECT COUNT(*) FILTER(WHERE status='nova')::int novas,COUNT(*) FILTER(WHERE status='em_analise')::int em_analise,COUNT(*) FILTER(WHERE status='backlog')::int backlog,COUNT(*) FILTER(WHERE status='em_desenvolvimento')::int em_desenvolvimento,COUNT(*) FILTER(WHERE status='homologacao')::int homologacao,COUNT(*) FILTER(WHERE status='concluido' AND completed_at>=date_trunc('month',NOW()))::int concluidas_mes,COALESCE(SUM(GREATEST(COALESCE(current_time_minutes,0)-COALESCE(automated_time_minutes,0),0)*COALESCE(executions_per_month,0)*COALESCE(people_involved,0))/60,0)::numeric(12,2) horas_economizadas_mes FROM development_requests`);const projects=await pool.query("SELECT COUNT(*)::int ativos FROM development_projects WHERE status NOT IN ('concluido','cancelado')");res.json({...result.rows[0],projetos_ativos:projects.rows[0].ativos});}catch(error){handle(res,error,req);}}

module.exports={listRequests,getRequest,createRequest,updateRequest,changeStatus,decide,deploy,convertProject,listProjects,getProject,createProject,addTask,dashboard};
