import { useState, type ChangeEvent, type FormEvent } from "react";
import { AlertTriangle, Building2, Check, Clock3, Eye, MessageSquare, Palette, Settings, Upload, Users } from "lucide-react";
import type { ConfiguracoesSistema, RespostaRapida } from "../../services/api";
type Section="identidade"|"sla"|"respostas"|"previa";
type Props={config:ConfiguracoesSistema;setConfig:(value:ConfiguracoesSistema)=>void;logo:string;uploading:boolean;onLogo:(event:ChangeEvent<HTMLInputElement>)=>void;onSave:(event:FormEvent)=>void;quick:{titulo:string;mensagem:string;categoria:string};setQuick:(value:{titulo:string;mensagem:string;categoria:string})=>void;onCreateQuick:(event:FormEvent)=>void;responses:RespostaRapida[];onNavigate:(tab:"teams"|"catalogos"|"manutencao")=>void};
const fields=[
 {key:"sla_critica",label:"Crítica",tone:"bg-rose-500",response:15,resolution:120},
 {key:"sla_alta",label:"Alta",tone:"bg-red-500",response:60,resolution:480},
 {key:"sla_media",label:"Média",tone:"bg-amber-500",response:240,resolution:1440},
 {key:"sla_baixa",label:"Baixa",tone:"bg-emerald-500",response:1440,resolution:2880},
];
export function SettingsWorkspace(p:Props){const [section,setSection]=useState<Section>("identidade");const set=(key:string,value:string)=>p.setConfig({...p.config,[key]:value});return <div className="settings-subpages grid gap-4 lg:grid-cols-[230px_minmax(0,1fr)]">
 <aside className="h-fit rounded-2xl border bg-white p-2 shadow-sm lg:sticky lg:top-4"><p className="px-3 pb-2 pt-3 text-[10px] font-black uppercase tracking-widest text-zinc-400">Configurações</p>{([['identidade',Palette,'Identidade','Marca e aparência'],['sla',Clock3,'SLA e prioridades','Prazos operacionais'],['respostas',MessageSquare,'Respostas rápidas','Mensagens reutilizáveis'],['previa',Eye,'Prévia','Resultado aplicado']] as const).map(([key,Icon,label,hint])=><button key={key} onClick={()=>setSection(key)} className={`mb-1 flex w-full items-center gap-3 rounded-xl p-3 text-left ${section===key?"bg-blue-600 text-white shadow-md":"text-zinc-600 hover:bg-zinc-50"}`}><Icon size={18}/><span><b className="block text-sm">{label}</b><small className={section===key?"text-white/70":"text-zinc-400"}>{hint}</small></span></button>)}<div className="my-2 border-t"/><p className="px-3 py-2 text-[10px] font-black uppercase tracking-widest text-zinc-400">Administração</p><Link icon={Users} label="Equipes" onClick={()=>p.onNavigate("teams")}/><Link icon={Building2} label="Catálogos" onClick={()=>p.onNavigate("catalogos")}/><Link icon={AlertTriangle} label="Manutenção" onClick={()=>p.onNavigate("manutencao")}/></aside>
 <section key={section} className="settings-section-enter rounded-2xl border bg-white p-5 shadow-sm md:p-6">
  {section==="identidade"&&<><Heading title="Identidade do sistema" text="Defina a marca exibida para usuários e equipe."/><form onSubmit={p.onSave} className="mt-6 max-w-3xl space-y-5"><div className="flex items-center gap-5 rounded-2xl border bg-zinc-50 p-4"><img src={p.logo} className="h-20 w-24 object-contain"/><div><b className="block">Logo principal</b><p className="text-xs text-zinc-500">PNG ou WebP com fundo transparente.</p><label className="mt-3 inline-flex cursor-pointer items-center gap-2 rounded-xl border bg-white px-3 py-2 text-xs font-black"><Upload size={15}/>{p.uploading?"Enviando...":"Escolher imagem"}<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={p.onLogo}/></label></div></div><Field label="Nome do sistema"><input value={String(p.config.nome_sistema||"")} onChange={e=>set("nome_sistema",e.target.value)}/></Field><Field label="E-mail de suporte"><input type="email" value={String(p.config.email_suporte||"")} onChange={e=>set("email_suporte",e.target.value)}/></Field><Field label="Cor principal"><div className="grid grid-cols-[64px_1fr] gap-2"><input type="color" value={String(p.config.cor_principal||"#2563eb")} onChange={e=>set("cor_principal",e.target.value)} className="p-1"/><input value={String(p.config.cor_principal||"#2563eb")} onChange={e=>set("cor_principal",e.target.value)}/></div></Field><Save/></form></>}
  {section==="sla"&&<><Heading title="SLA e prioridades" text="Configure resposta e resolução em minutos para cada nível."/><form onSubmit={p.onSave} className="mt-6 max-w-4xl space-y-3">{fields.map(f=><div key={f.key} className="grid items-center gap-3 rounded-2xl border p-4 md:grid-cols-[150px_1fr_1fr]"><div className="flex items-center gap-3"><i className={`h-3 w-3 rounded-full ${f.tone}`}/><b>{f.label}</b></div><Field label="Primeira resposta"><input type="number" min="1" value={String(p.config[`${f.key}_resposta`]||f.response)} onChange={e=>set(`${f.key}_resposta`,e.target.value)}/></Field><Field label="Resolução"><input type="number" min="1" value={String(p.config[`${f.key}_resolucao`]||f.resolution)} onChange={e=>set(`${f.key}_resolucao`,e.target.value)}/></Field></div>)}<Save/></form></>}
  {section==="respostas"&&<><Heading title="Respostas rápidas" text="Cadastre mensagens padronizadas para reduzir o tempo de atendimento."/><div className="mt-6 grid gap-5 xl:grid-cols-[380px_1fr]"><form onSubmit={p.onCreateQuick} className="space-y-4 rounded-2xl border bg-zinc-50 p-4"><Field label="Título"><input value={p.quick.titulo} onChange={e=>p.setQuick({...p.quick,titulo:e.target.value})}/></Field><Field label="Categoria"><input value={p.quick.categoria} onChange={e=>p.setQuick({...p.quick,categoria:e.target.value})}/></Field><Field label="Mensagem"><textarea rows={6} value={p.quick.mensagem} onChange={e=>p.setQuick({...p.quick,mensagem:e.target.value})}/></Field><Save label="Criar resposta"/></form><div className="space-y-2">{p.responses.map(r=><article key={r.id} className="rounded-2xl border p-4"><div className="flex justify-between"><b>{r.titulo}</b><span className="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-black text-blue-700">{r.categoria}</span></div><p className="mt-2 text-sm leading-6 text-zinc-600">{r.mensagem}</p></article>)}{!p.responses.length&&<Empty text="Nenhuma resposta rápida cadastrada."/>}</div></div></>}
  {section==="previa"&&<><Heading title="Prévia aplicada" text="Confira como a identidade está configurada atualmente."/><div className="mt-8 grid max-w-4xl gap-4 sm:grid-cols-2"><Preview label="Logo"><img src={p.logo} className="h-20 w-28 object-contain"/></Preview><Preview label="Nome"><b className="text-xl">{String(p.config.nome_sistema||"Smart HelpDesk")}</b></Preview><Preview label="Suporte"><b className="text-blue-600">{String(p.config.email_suporte||"")}</b></Preview><Preview label="Cor principal"><div className="h-12 rounded-xl" style={{background:String(p.config.cor_principal||"#2563eb")}}/></Preview></div></>}
 </section></div>}
function Heading({title,text}:{title:string;text:string}){return <div><p className="flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-blue-600"><Settings size={14}/>Ajustes</p><h3 className="mt-2 text-xl font-black">{title}</h3><p className="mt-1 text-sm text-zinc-500">{text}</p></div>}
function Field({label,children}:{label:string;children:any}){return <label className="block"><span className="mb-1.5 block text-[10px] font-black uppercase tracking-wide text-zinc-500">{label}</span>{children}</label>}
function Save({label="Salvar alterações"}:{label?:string}){return <button className="inline-flex h-10 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-black text-white"><Check size={16}/>{label}</button>}
function Link({icon:Icon,label,onClick}:{icon:any;label:string;onClick:()=>void}){return <button onClick={onClick} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold text-zinc-600 hover:bg-zinc-50"><Icon size={17}/>{label}</button>}
function Preview({label,children}:{label:string;children:any}){return <div className="rounded-2xl border bg-zinc-50 p-5"><p className="mb-3 text-xs font-black text-zinc-500">{label}</p>{children}</div>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed p-8 text-center text-sm text-zinc-500">{text}</div>}
