CREATE TABLE IF NOT EXISTS performance_ratings (
  id SERIAL PRIMARY KEY, ticket_id INTEGER NOT NULL REFERENCES chamados(id) ON DELETE CASCADE, technician_id INTEGER REFERENCES usuarios(id) ON DELETE SET NULL, team_id INTEGER REFERENCES teams(id) ON DELETE SET NULL, client_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  overall_rating SMALLINT NOT NULL CHECK (overall_rating BETWEEN 1 AND 5), courtesy_rating SMALLINT NOT NULL CHECK (courtesy_rating BETWEEN 1 AND 5), communication_rating SMALLINT NOT NULL CHECK (communication_rating BETWEEN 1 AND 5), resolution_rating SMALLINT NOT NULL CHECK (resolution_rating BETWEEN 1 AND 5), speed_rating SMALLINT NOT NULL CHECK (speed_rating BETWEEN 1 AND 5), nps_score SMALLINT NOT NULL CHECK (nps_score BETWEEN 0 AND 10), comment TEXT, sentiment VARCHAR(16) NOT NULL DEFAULT 'neutral' CHECK (sentiment IN ('positive','neutral','negative')), sentiment_score NUMERIC(5,2) NOT NULL DEFAULT 0, keywords JSONB NOT NULL DEFAULT '[]'::jsonb, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(ticket_id, client_id)
);
CREATE TABLE IF NOT EXISTS performance_scores (
  id SERIAL PRIMARY KEY, technician_id INTEGER REFERENCES usuarios(id) ON DELETE CASCADE, team_id INTEGER REFERENCES teams(id) ON DELETE CASCADE, month SMALLINT NOT NULL CHECK (month BETWEEN 1 AND 12), year SMALLINT NOT NULL CHECK (year >= 2020), performance_score NUMERIC(5,2) NOT NULL DEFAULT 0, average_rating NUMERIC(4,2) NOT NULL DEFAULT 0, average_resolution_time NUMERIC(12,2) NOT NULL DEFAULT 0, sla_rate NUMERIC(5,2) NOT NULL DEFAULT 0, first_contact_resolution_rate NUMERIC(5,2) NOT NULL DEFAULT 0, reopen_rate NUMERIC(5,2) NOT NULL DEFAULT 0, productivity_score NUMERIC(5,2) NOT NULL DEFAULT 0, total_closed_tickets INTEGER NOT NULL DEFAULT 0, total_ratings INTEGER NOT NULL DEFAULT 0, nps_average NUMERIC(5,2) NOT NULL DEFAULT 0, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_performance_scores_scope_period ON performance_scores (COALESCE(technician_id, 0), COALESCE(team_id, 0), month, year);
CREATE INDEX IF NOT EXISTS idx_performance_ratings_technician_created ON performance_ratings(technician_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_performance_ratings_team_created ON performance_ratings(team_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_performance_ratings_client_ticket ON performance_ratings(client_id, ticket_id);
