import { useEffect, useMemo, useState } from "react";
import { Activity, ChevronRight, Clock3, Filter, MapPinned, RefreshCw, X } from "lucide-react";
import { toast } from "sonner";
import "leaflet/dist/leaflet.css";
import "./patrimonio-map.css";
import { municipiosMaranhao } from "../../data/municipiosMaranhao";
import { createAgentInvite, deriveDeviceAlerts, getAssetLocations, getDeviceHistory, getDevices, getMunicipioSummary, updateDeviceLocation, updateDeviceStatus } from "../../services/deviceService";
import { criarChamado } from "../../services/api";
import type { Device, DeviceAlert, DeviceHistory, MunicipioSummary as Summary } from "../../types/device";
import { AlertsList } from "../../components/patrimonio/AlertsList";
import { DeviceDetails } from "../../components/patrimonio/DeviceDetails";
import { DeviceDiagnostics } from "../../components/patrimonio/DeviceDiagnostics";
import { DeviceFilters, type PatrimonioFilters } from "../../components/patrimonio/DeviceFilters";
import { MunicipioDevices } from "../../components/patrimonio/MunicipioDevices";
import { MunicipioSummary } from "../../components/patrimonio/MunicipioSummary";
import { PatrimonioMap } from "../../components/patrimonio/PatrimonioMap";
import { PatrimonioStats } from "../../components/patrimonio/PatrimonioStats";

const emptyFilters: PatrimonioFilters = { status: "all", municipio: "", query: "" };
export function PatrimonioMapPage({ dark = false }: { dark?: boolean }) {
  const [devices, setDevices] = useState<Device[]>([]), [alerts, setAlerts] = useState<DeviceAlert[]>([]), [summary, setSummary] = useState<Summary[]>([]);
  const [selected, setSelected] = useState<Device | null>(null), [expanded, setExpanded] = useState(false), [loading, setLoading] = useState(true), [filtersOpen, setFiltersOpen] = useState(false);
  const [history, setHistory] = useState<DeviceHistory[]>([]), [historyOpen, setHistoryOpen] = useState(false), [lastUpdated, setLastUpdated] = useState(new Date());
  const [diagnostics,setDiagnostics]=useState<Device|null>(null),[diagnosticsRefreshing,setDiagnosticsRefreshing]=useState(false);
  const [filters, setFilters] = useState<PatrimonioFilters>(() => { try { return JSON.parse(localStorage.getItem("patrimonio-filtros") || "null") || emptyFilters; } catch { return emptyFilters; } });
  useEffect(()=>{const handler=(event:Event)=>setDiagnostics((event as CustomEvent<Device>).detail);window.addEventListener("asset-diagnostics-open",handler);return()=>window.removeEventListener("asset-diagnostics-open",handler)},[]);
  async function refreshDiagnostics(){if(!diagnostics)return;setDiagnosticsRefreshing(true);try{const rows=await getDevices();setDevices(rows);const updated=rows.find(row=>row.id===diagnostics.id);if(updated)setDiagnostics(updated);setLastUpdated(new Date());toast.success("Diagnóstico atualizado com os dados mais recentes do servidor.");}catch(e){toast.error(e instanceof Error?e.message:"Erro ao atualizar diagnóstico");}finally{setDiagnosticsRefreshing(false)}}

  async function reload() { try { const rows=await getDevices(); setDevices(rows); setAlerts(deriveDeviceAlerts(rows)); setSummary(await getMunicipioSummary()); setLastUpdated(new Date()); } catch(e) { toast.error(e instanceof Error?e.message:"Erro ao carregar ativos"); } finally { setLoading(false); } }
  useEffect(() => { reload(); const timer=window.setInterval(reload,30000); return () => clearInterval(timer); }, []);
  useEffect(() => localStorage.setItem("patrimonio-filtros", JSON.stringify(filters)), [filters]);
  const filtered = useMemo(() => { const q = filters.query.trim().toLowerCase(); return devices.filter((d) => (filters.status === "all" || d.status === filters.status) && (!filters.municipio || d.municipio === filters.municipio) && (!q || [d.hostname,d.patrimonio,d.usuario,d.ip].some((v) => v.toLowerCase().includes(q)))); }, [devices, filters]);
  const cityDevices = useMemo(() => devices.filter((d) => d.municipio === filters.municipio), [devices, filters.municipio]);
  const activeFilters = Number(filters.status !== "all") + Number(!!filters.municipio) + Number(!!filters.query);
  async function action(type: string, device: Device) { if(type==="diagnostico"){setDiagnostics(device);return;} if (type === "historico") { setHistory(await getDeviceHistory(device.id)); setHistoryOpen(true); return; } if (type.startsWith("status:")) { try { const status=type.slice(7) as Device["status"]; const updated=await updateDeviceStatus(device.id,status); setSelected(updated); await reload(); toast.success(`Estado de ${device.hostname} atualizado.`); } catch(e) { toast.error(e instanceof Error?e.message:"Não foi possível atualizar o estado."); } return; } if (type === "chamado") { try { const ticket = await criarChamado({ titulo: `[Ativo ${device.patrimonio}] ${device.hostname} requer atendimento`, descricao: `Chamado aberto pelo Monitoramento de Ativos.\n\nMunicípio: ${device.municipio}\nUnidade: ${device.unidade}\nHostname: ${device.hostname}\nPatrimônio: ${device.patrimonio}\nIP: ${device.ip}\nStatus: ${device.status}\nCPU: ${Math.round(device.cpuUsage)}% | RAM: ${Math.round(device.ramUsage)}% | Disco: ${Math.round(device.diskUsage)}%`, tipo_chamado: "Incidente" }); toast.success(`Chamado ${ticket.numero_chamado || `#${ticket.id}`} aberto com sucesso.`); } catch (e) { toast.error(e instanceof Error ? e.message : "Não foi possível abrir o chamado."); } } }
  async function correctLocation(device:Device){try{const locations=await getAssetLocations();const options=locations.map((l,i)=>`${i+1}. ${l.municipio} — ${l.nome}`).join("\n");const choice=window.prompt(`Escolha a unidade correta:\n\n${options}\n\nDigite o número:`);if(!choice)return;const location=locations[Number(choice)-1];if(!location){toast.error("Opção inválida.");return;}if(!window.confirm(`Confirma mover ${device.hostname} para ${location.nome}, ${location.municipio}?`))return;const updated=await updateDeviceLocation(device.id,location);setSelected(updated);await reload();toast.success("Localização atualizada com sucesso.");}catch(e){toast.error(e instanceof Error?e.message:"Erro ao atualizar localização");}}
  useEffect(()=>{const handler=(event:Event)=>correctLocation((event as CustomEvent<Device>).detail);window.addEventListener("asset-location-correct",handler);return()=>window.removeEventListener("asset-location-correct",handler);},[]);
  const selectCity = (municipio: string) => { setSelected(null); setFilters((old) => ({ ...old, municipio })); };
  async function generateInvite(){try{const result=await createAgentInvite(2);await navigator.clipboard?.writeText(result.convite);window.prompt(`Convite de uso único, válido por 2 horas. Envie junto com a pasta do agente.\n\nO código também foi copiado quando permitido pelo navegador:`,result.convite);toast.success("Convite criado. Ele será invalidado após o primeiro cadastro.");}catch(e){toast.error(e instanceof Error?e.message:"Erro ao gerar convite");}}
  return <div className={`space-y-3 patrimonio-module ${dark ? "patrimonio-dark" : ""}`}>
    <header className="flex flex-wrap items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><Activity size={20}/></span><div className="min-w-0 flex-1"><h2 className="truncate text-lg font-black">Monitoramento de Ativos</h2><p className="truncate text-xs text-zinc-500">Área de Atuação Maranhão Motos · atualizado às {lastUpdated.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</p></div><button onClick={generateInvite} className="h-10 rounded-xl bg-blue-600 px-4 text-xs font-black text-white">Gerar convite do agente</button><button onClick={() => setFiltersOpen(true)} className="relative flex h-10 items-center gap-2 rounded-xl border bg-white px-3 text-xs font-black shadow-sm"><Filter size={16}/>Filtros{activeFilters > 0 && <span className="grid h-5 min-w-5 place-items-center rounded-full bg-blue-600 px-1 text-white">{activeFilters}</span>}</button><button onClick={reload} className="grid h-10 w-10 place-items-center rounded-xl border bg-white"><RefreshCw size={17}/></button></header>
    <PatrimonioStats devices={devices}/>
    {loading ? <div className="grid h-[620px] place-items-center rounded-2xl border bg-white"><RefreshCw className="animate-spin text-blue-600"/></div> : <div className="grid min-h-[640px] gap-4 xl:grid-cols-[minmax(0,1fr)_370px]"><div className="map-stage relative min-h-[640px] overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="pointer-events-none absolute left-4 top-4 z-[500] rounded-xl bg-white/90 px-3 py-2 shadow-lg backdrop-blur"><b className="text-xs">Área Maranhão Motos · {filtered.length} ativos visíveis</b><div className="mt-1 flex gap-3 text-[10px] font-bold text-zinc-500"><span>🟢 Online</span><span>🟠 Atenção</span><span>🔴 Offline</span></div></div><PatrimonioMap devices={filtered} allDevices={devices} selected={selected} municipio={filters.municipio} onSelect={setSelected} onMunicipioSelect={selectCity}/></div>{selected ? <DeviceDetails device={selected} onAction={action} onClose={() => setSelected(null)}/> : filters.municipio ? <MunicipioDevices municipio={filters.municipio} devices={cityDevices} onSelect={setSelected} onClear={() => setFilters((old) => ({...old,municipio:""}))}/> : <aside className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-blue-700"><MapPinned/></span><div><h3 className="font-black">Cobertura regional</h3><p className="text-xs text-zinc-500">27 municípios da área de atuação</p></div></div><div className="mt-5 space-y-2">{summary.slice(0,12).map((row)=><button key={row.municipio} onClick={()=>selectCity(row.municipio)} className="flex w-full items-center gap-3 rounded-xl border border-zinc-100 p-3 text-left hover:bg-blue-50"><span className="grid h-9 w-9 place-items-center rounded-xl bg-blue-50 text-xs font-black text-blue-700">{row.total}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{row.municipio}</b><small className="text-zinc-500">{row.online} online · {row.warning+row.offline} alertas</small></span><ChevronRight size={16}/></button>)}</div></aside>}</div>}
    <div className="grid gap-4 xl:grid-cols-[380px_minmax(0,1fr)]"><AlertsList alerts={alerts.slice(0,8)} onSelect={(id) => { const d=devices.find((x)=>x.id===id); if(d){setFilters((old)=>({...old,municipio:d.municipio}));setSelected(d);} }}/><MunicipioSummary rows={summary} expanded={expanded} onToggle={()=>setExpanded(!expanded)} onSelect={selectCity}/></div>
    {filtersOpen && <div className="fixed inset-0 z-[80] flex justify-end"><button aria-label="Fechar" onClick={()=>setFiltersOpen(false)} className="absolute inset-0 bg-slate-950/35"/><aside className="relative z-10 h-full w-full max-w-md overflow-y-auto bg-white p-5 shadow-2xl"><div className="flex justify-between"><div><b className="flex items-center gap-2"><Filter size={18}/>Filtros do mapa</b><p className="mt-1 text-xs text-zinc-500">Os filtros ficam salvos neste navegador.</p></div><button onClick={()=>setFiltersOpen(false)}><X/></button></div><div className="mt-6"><DeviceFilters filters={filters} municipios={municipiosMaranhao.map((m)=>m.nome)} onChange={setFilters}/></div><div className="mt-5 grid grid-cols-2 gap-3"><button onClick={()=>setFilters(emptyFilters)} className="rounded-xl border py-3 text-sm font-black">Limpar</button><button onClick={()=>setFiltersOpen(false)} className="rounded-xl bg-blue-600 py-3 text-sm font-black text-white">Ver resultados ({filtered.length})</button></div></aside></div>}
    {historyOpen && <div className="fixed inset-0 z-[90] flex justify-end"><button aria-label="Fechar" onClick={()=>setHistoryOpen(false)} className="absolute inset-0 bg-slate-950/35"/><aside className="relative z-10 h-full w-full max-w-md overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-black text-blue-600">LINHA DO TEMPO</p><h3 className="text-xl font-black">Histórico do ativo</h3></div><button onClick={()=>setHistoryOpen(false)}><X/></button></div><div className="mt-7 space-y-3">{history.map((item)=><div key={item.id} className="rounded-xl border p-4"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600"><Clock3 size={16}/></span><div><b className="text-sm">{item.titulo}</b><p className="mt-1 text-xs leading-5 text-zinc-500">{item.descricao}</p><time className="mt-2 block text-[10px] font-bold text-zinc-400">{new Date(item.horario).toLocaleString("pt-BR")}</time></div></div></div>)}</div></aside></div>}
    {diagnostics&&<DeviceDiagnostics device={diagnostics} onClose={()=>setDiagnostics(null)} onRefresh={refreshDiagnostics} refreshing={diagnosticsRefreshing} onAction={action}/>}  </div>;
}
