import { useMemo, useState, type ReactNode } from "react";
import { Activity, AlertTriangle, ArrowRight, BarChart3, CheckCircle2, Clock3, Filter, MapPin, Monitor, PauseCircle, RotateCcw, Ticket, UserRound, Users, X } from "lucide-react";
import type { ApiChamado } from "../../services/api";
import { TICKET_STATUS, canonicalTicketStatus } from "../../domain/ticketStatus";

type Section="operation"|"sla"|"technicians"|"assets";
type MetricFilter="all"|"open"|"resolved"|"unassigned"|"critical"|"risk"|"violated"|"paused"|"assets";
type Metric={label:string;value:string|number;hint:string;icon:typeof Ticket;tone:string;filter:MetricFilter};
const finalStatus=(c:ApiChamado)=>[TICKET_STATUS.CLOSED,TICKET_STATUS.RESOLVED,TICKET_STATUS.CANCELED].includes(canonicalTicketStatus(c.status) as typeof TICKET_STATUS.CLOSED);
const critical=(c:ApiChamado)=>["crítica","critica"].includes(String(c.prioridade||"").toLowerCase());
const atRisk=(c:ApiChamado)=>c.sla_status==="alerta";
const violated=(c:ApiChamado)=>c.sla_status==="vencido"||Boolean(c.vencido)||Boolean(c.finalizado_em&&c.sla_limite_resolucao&&new Date(c.finalizado_em)>new Date(c.sla_limite_resolucao));
const paused=(c:ApiChamado)=>c.sla_status==="pausado"||canonicalTicketStatus(c.status)===TICKET_STATUS.WAITING_USER;
const requester=(c:ApiChamado)=>c.solicitante_nome||c.solicitante||c.email_solicitante||"Solicitante";
const owner=(c:ApiChamado)=>c.responsavel_nome||c.responsavel||"Sem responsável";
const city=(c:ApiChamado)=>c.municipio_solicitante||c.ativo_municipio||"Não informado";
const openedAt=(c:ApiChamado)=>c.criado_em?new Date(c.criado_em):null;
function minutes(a?:string|null,b?:string|null){if(!a||!b)return null;const value=(new Date(b).getTime()-new Date(a).getTime())/60000;return Number.isFinite(value)&&value>=0?value:null}
function duration(value:number|null){if(value==null)return "Sem base";if(value<60)return `${Math.round(value)} min`;const hours=Math.floor(value/60),mins=Math.round(value%60);return `${hours}h ${mins}min`}
function average(values:Array<number|null>){const valid=values.filter((v):v is number=>v!=null);return valid.length?valid.reduce((a,b)=>a+b,0)/valid.length:null}
function percent(value:number,total:number){return total?Math.round(value/total*100):0}
function filterTickets(items:ApiChamado[],filter:MetricFilter){if(filter==="open")return items.filter(c=>!finalStatus(c));if(filter==="resolved")return items.filter(finalStatus);if(filter==="unassigned")return items.filter(c=>!finalStatus(c)&&!c.responsavel_id&&!c.responsavel);if(filter==="critical")return items.filter(c=>!finalStatus(c)&&critical(c));if(filter==="risk")return items.filter(atRisk);if(filter==="violated")return items.filter(violated);if(filter==="paused")return items.filter(paused);if(filter==="assets")return items.filter(c=>Boolean(c.ativo_id));return items}

export function IndicatorsWorkspace({section,chamados,onOpen}:{section:Section;chamados:ApiChamado[];onOpen?:(id:number)=>void}){
 const [period,setPeriod]=useState(30),[municipality,setMunicipality]=useState(""),[priority,setPriority]=useState(""),[detail,setDetail]=useState<MetricFilter>("all");
 const municipalities=useMemo(()=>Array.from(new Set(chamados.map(city).filter(v=>v!=="Não informado"))).sort((a,b)=>a.localeCompare(b,"pt-BR")),[chamados]);
 const base=useMemo(()=>{const since=Date.now()-period*86400000;return chamados.filter(c=>{const opened=openedAt(c);return (!opened||opened.getTime()>=since)&&(!municipality||city(c)===municipality)&&(!priority||c.prioridade===priority)})},[chamados,period,municipality,priority]);
 const previous=useMemo(()=>{const end=Date.now()-period*86400000,start=end-period*86400000;return chamados.filter(c=>{const opened=openedAt(c)?.getTime();return opened!=null&&opened>=start&&opened<end&&(!municipality||city(c)===municipality)&&(!priority||c.prioridade===priority)})},[chamados,period,municipality,priority]);
 const open=base.filter(c=>!finalStatus(c)),resolved=base.filter(finalStatus),unassigned=open.filter(c=>!c.responsavel_id&&!c.responsavel),risks=base.filter(atRisk),violations=base.filter(violated),pauses=base.filter(paused),assetTickets=base.filter(c=>Boolean(c.ativo_id)),criticals=open.filter(critical);
 const complianceBase=resolved.filter(c=>c.finalizado_em&&c.sla_limite_resolucao),compliant=complianceBase.filter(c=>!violated(c)),compliance=percent(compliant.length,complianceBase.length);
 const responseAvg=average(base.map(c=>minutes(c.criado_em,c.primeira_resposta_em))),resolutionAvg=average(resolved.map(c=>minutes(c.criado_em,c.finalizado_em)));
 const trend=previous.length?Math.round((base.length-previous.length)/previous.length*100):base.length?100:0;
 const metrics:Metric[]=section==="sla"?[
  {label:"Conformidade SLA",value:complianceBase.length?`${compliance}%`:"Sem base",hint:`${compliant.length} de ${complianceBase.length} concluídos`,icon:CheckCircle2,tone:"emerald",filter:"resolved"},
  {label:"Em risco",value:risks.length,hint:"Próximos do vencimento",icon:Clock3,tone:"amber",filter:"risk"},
  {label:"SLA vencido",value:violations.length,hint:"Exigem tratamento",icon:AlertTriangle,tone:"red",filter:"violated"},
  {label:"SLA pausado",value:pauses.length,hint:"Aguardando usuário",icon:PauseCircle,tone:"violet",filter:"paused"},
  {label:"Primeira resposta",value:duration(responseAvg),hint:"Tempo médio",icon:Activity,tone:"blue",filter:"all"},
  {label:"Resolução média",value:duration(resolutionAvg),hint:"Chamados concluídos",icon:RotateCcw,tone:"cyan",filter:"resolved"},
 ]:section==="assets"?[
  {label:"Com ativo vinculado",value:assetTickets.length,hint:`${percent(assetTickets.length,base.length)}% da base`,icon:Monitor,tone:"blue",filter:"assets"},
  {label:"Ativos com chamados abertos",value:assetTickets.filter(c=>!finalStatus(c)).length,hint:"Demanda ativa",icon:Ticket,tone:"amber",filter:"assets"},
  {label:"Críticos com ativo",value:assetTickets.filter(c=>!finalStatus(c)&&critical(c)).length,hint:"Prioridade imediata",icon:AlertTriangle,tone:"red",filter:"critical"},
  {label:"Resolvidos com ativo",value:assetTickets.filter(finalStatus).length,hint:"No período",icon:CheckCircle2,tone:"emerald",filter:"assets"},
  {label:"Cidades atendidas",value:new Set(assetTickets.map(city)).size,hint:"Cobertura operacional",icon:MapPin,tone:"violet",filter:"assets"},
  {label:"SLA vencido",value:assetTickets.filter(violated).length,hint:"Chamados de equipamento",icon:Clock3,tone:"red",filter:"violated"},
 ]:[
  {label:"Recebidos",value:base.length,hint:`${trend>=0?"+":""}${trend}% vs. período anterior`,icon:Ticket,tone:"blue",filter:"all"},
  {label:"Backlog",value:open.length,hint:`${percent(open.length,base.length)}% da base`,icon:Activity,tone:"amber",filter:"open"},
  {label:"Resolvidos",value:resolved.length,hint:`${percent(resolved.length,base.length)}% da base`,icon:CheckCircle2,tone:"emerald",filter:"resolved"},
  {label:"Sem responsável",value:unassigned.length,hint:"Aguardando distribuição",icon:UserRound,tone:"violet",filter:"unassigned"},
  {label:"SLA em risco",value:risks.length,hint:"Ação preventiva",icon:Clock3,tone:"amber",filter:"risk"},
  {label:"Críticos",value:criticals.length,hint:"Em aberto",icon:AlertTriangle,tone:"red",filter:"critical"},
 ];
 const detailTickets=filterTickets(base,detail).slice(0,50);
 const regions=distribution(base,city),statuses=distribution(base,c=>statusLabel(c.status)),priorities=distribution(base,c=>c.prioridade||"Não informada"),categories=distribution(base,c=>c.categoria_ia||c.tipo_chamado||"Não classificada");
 const technicians=technicianRows(base);
 const series=dailySeries(base,Math.min(period,30));
 const title=section==="sla"?"Desempenho de SLA":section==="technicians"?"Capacidade da equipe":section==="assets"?"Chamados e ativos":"Visão operacional";
 return <div className="ds-page indicators-workspace">
  <section className="border-b bg-[var(--ds-surface)] px-4 py-3 sm:px-5"><div className="flex flex-wrap items-center gap-3"><div className="mr-auto"><p className="text-[10px] font-black uppercase tracking-[.14em] text-blue-600">Inteligência operacional</p><h2 className="mt-1 text-lg font-black">{title}</h2><p className="mt-0.5 text-xs text-slate-500">Dados reais · {base.length} registro(s) analisados · comparação com período anterior</p></div><div className="flex flex-wrap items-center gap-2"><Select value={period} onChange={e=>setPeriod(Number(e.target.value))} label="Período"><option value={1}>Hoje</option><option value={7}>7 dias</option><option value={30}>30 dias</option><option value={90}>90 dias</option><option value={365}>12 meses</option></Select><Select value={municipality} onChange={e=>setMunicipality(e.target.value)} label="Área"><option value="">Todas as áreas</option>{municipalities.map(item=><option key={item}>{item}</option>)}</Select><Select value={priority} onChange={e=>setPriority(e.target.value)} label="Prioridade"><option value="">Todas</option>{["Crítica","Alta","Média","Baixa"].map(item=><option key={item}>{item}</option>)}</Select>{(municipality||priority)&&<button className="ds-button ds-button--secondary inline-flex items-center gap-2" onClick={()=>{setMunicipality("");setPriority("")}}><X size={14}/>Limpar</button>}</div></div></section>
  <div className="space-y-4 p-4 sm:p-5">
   <section className="grid gap-px overflow-hidden border bg-[var(--ds-border)] sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">{metrics.map(metric=><MetricButton key={metric.label} metric={metric} active={detail===metric.filter} onClick={()=>setDetail(metric.filter)}/>)}</section>
   {section==="technicians"?<Technicians rows={technicians}/>:<>
    <section className="grid gap-4 xl:grid-cols-[minmax(0,1.55fr)_minmax(320px,.85fr)]"><Panel title="Evolução do período" subtitle="Tendência diária dos chamados recebidos" icon={<BarChart3 size={17}/>}><DailyAreaChart items={series}/></Panel><Panel title={section==="assets"?"Distribuição regional dos ativos":"Situação dos chamados"} subtitle={section==="assets"?"Participação das principais cidades":"Composição percentual da base filtrada"} icon={<Activity size={17}/>}><DonutChart rows={section==="assets"?distribution(assetTickets,city):statuses}/></Panel></section>
    <section className="grid gap-4 lg:grid-cols-3"><Panel title="Por área de atuação" subtitle={`${regions.length} localidade(s) com registros`} icon={<MapPin size={17}/>}><Distribution rows={regions}/></Panel><Panel title="Por prioridade" subtitle="Comparação direta do impacto operacional" icon={<AlertTriangle size={17}/>}><VerticalBars rows={priorities}/></Panel><Panel title="Por categoria" subtitle="Participação dos principais motivos" icon={<Ticket size={17}/>}><StackedDistribution rows={categories}/></Panel></section>
   </>}
   <DetailTable tickets={detailTickets} total={filterTickets(base,detail).length} filter={detail} onOpen={onOpen}/>
   <footer className="flex flex-wrap items-center gap-2 border-t pt-3 text-[10px] text-slate-500"><Filter size={13}/><b>Definições:</b><span>Conformidade usa chamados concluídos com datas de finalização e limite disponíveis.</span><span>·</span><span>Ativos usam vínculo real por ativo_id.</span><span>·</span><span>SLA pausado não é contabilizado como vencido.</span></footer>
  </div>
 </div>
}

const tones:Record<string,string>={blue:"bg-blue-50 text-blue-600",amber:"bg-amber-50 text-amber-600",red:"bg-red-50 text-red-600",emerald:"bg-emerald-50 text-emerald-600",violet:"bg-violet-50 text-violet-600",cyan:"bg-cyan-50 text-cyan-600"};
function MetricButton({metric,active,onClick}:{metric:Metric;active:boolean;onClick:()=>void}){const Icon=metric.icon;return <button onClick={onClick} className={`min-h-32 bg-[var(--ds-surface)] p-4 text-left transition hover:bg-[var(--ds-surface-subtle)] ${active?"inset-ring-2 inset-ring-blue-500":""}`}><div className="flex items-start justify-between"><span className={`grid h-9 w-9 place-items-center rounded-md ${tones[metric.tone]}`}><Icon size={17}/></span><ArrowRight size={14} className="text-slate-300"/></div><strong className="mt-3 block text-2xl tracking-tight">{metric.value}</strong><p className="mt-1 text-[10px] font-black uppercase tracking-wider text-slate-500">{metric.label}</p><small className="mt-1 block text-[10px] text-slate-400">{metric.hint}</small></button>}
function Select({children,label,...props}:{children:ReactNode;label:string}&React.SelectHTMLAttributes<HTMLSelectElement>){return <label className="block"><span className="sr-only">{label}</span><select {...props} className="h-10 min-w-32 border px-3 text-xs font-bold">{children}</select></label>}
function Panel({title,subtitle,icon,children}:{title:string;subtitle:string;icon:ReactNode;children:ReactNode}){return <section className="overflow-hidden border bg-[var(--ds-surface)]"><header className="flex items-start gap-2 border-b px-4 py-3"><span className="mt-0.5 text-blue-600">{icon}</span><div><h3 className="text-sm font-black">{title}</h3><p className="mt-0.5 text-[10px] text-slate-500">{subtitle}</p></div></header><div className="p-4">{children}</div></section>}
function Distribution({rows}:{rows:Array<{label:string;value:number}>}){const max=Math.max(1,...rows.map(r=>r.value)),total=rows.reduce((s,r)=>s+r.value,0);return <div className="space-y-3">{rows.slice(0,8).map(row=><div key={row.label}><div className="mb-1 flex items-center justify-between gap-3 text-xs"><span className="truncate font-bold">{row.label}</span><span className="shrink-0 text-slate-500">{row.value} · {percent(row.value,total)}%</span></div><div className="h-1.5 overflow-hidden bg-slate-100"><div className="h-full bg-blue-600" style={{width:`${row.value/max*100}%`}}/></div></div>)}{!rows.length&&<p className="py-8 text-center text-xs text-slate-400">Sem dados para esta seleção.</p>}</div>}
const chartColors=["#0ea5e9","#22c55e","#f59e0b","#8b5cf6","#ef4444","#06b6d4","#64748b","#ec4899"];
function DailyAreaChart({items}:{items:Array<{label:string;value:number}>}){const width=720,height=210,pad=24,max=Math.max(1,...items.map(i=>i.value)),step=(width-pad*2)/Math.max(1,items.length-1),points=items.map((item,index)=>`${pad+index*step},${height-pad-item.value/max*(height-pad*2)}`).join(" "),area=`${pad},${height-pad} ${points} ${width-pad},${height-pad}`;return <div><svg viewBox={`0 0 ${width} ${height}`} className="h-52 w-full overflow-visible" role="img" aria-label="Gráfico de área da evolução diária"><defs><linearGradient id="indicator-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#0ea5e9" stopOpacity=".38"/><stop offset="1" stopColor="#0ea5e9" stopOpacity=".03"/></linearGradient></defs>{[0,1,2,3,4].map(i=><line key={i} x1={pad} x2={width-pad} y1={pad+i*(height-pad*2)/4} y2={pad+i*(height-pad*2)/4} stroke="currentColor" className="text-slate-200" strokeWidth="1"/>)}<polygon points={area} fill="url(#indicator-area)"/><polyline points={points} fill="none" stroke="#0284c7" strokeWidth="4" strokeLinejoin="round" strokeLinecap="round"/>{items.map((item,index)=><circle key={index} cx={pad+index*step} cy={height-pad-item.value/max*(height-pad*2)} r="4" fill="#fff" stroke="#0284c7" strokeWidth="3"><title>{item.label}: {item.value}</title></circle>)}</svg><div className="flex justify-between text-[10px] font-semibold text-slate-500"><span>{items[0]?.label}</span><span>Pico: {max}</span><span>{items.at(-1)?.label}</span></div></div>}
function DonutChart({rows}:{rows:Array<{label:string;value:number}>}){const visible=rows.slice(0,6),total=visible.reduce((sum,row)=>sum+row.value,0),gradient=visible.length?visible.map((row,index)=>{const before=visible.slice(0,index).reduce((sum,item)=>sum+item.value,0)/Math.max(1,total)*100,after=(visible.slice(0,index+1).reduce((sum,item)=>sum+item.value,0)/Math.max(1,total))*100;return `${chartColors[index%chartColors.length]} ${before}% ${after}%`}).join(","):"#e2e8f0 0 100%";return <div className="grid min-h-56 items-center gap-5 sm:grid-cols-[150px_1fr]"><div className="relative mx-auto h-36 w-36 rounded-full" style={{background:`conic-gradient(${gradient})`}}><div className="absolute inset-7 grid place-items-center rounded-full bg-[var(--ds-surface)] text-center"><b className="text-2xl">{total}</b><span className="text-[10px] text-slate-500">registros</span></div></div><div className="space-y-2">{visible.map((row,index)=><div key={row.label} className="flex items-center gap-2 text-xs"><i className="h-3 w-3 rounded-sm" style={{background:chartColors[index%chartColors.length]}}/><span className="min-w-0 flex-1 truncate font-semibold">{row.label}</span><b>{percent(row.value,total)}%</b></div>)}</div></div>}
function VerticalBars({rows}:{rows:Array<{label:string;value:number}>}){const visible=rows.slice(0,6),max=Math.max(1,...visible.map(row=>row.value));return <div className="flex h-56 items-end justify-around gap-3 border-b px-2 pt-6">{visible.map((row,index)=><div key={row.label} className="flex h-full min-w-0 flex-1 flex-col items-center justify-end gap-2"><b className="text-xs">{row.value}</b><div className="w-full max-w-12 rounded-t-sm" style={{height:`${Math.max(5,row.value/max*155)}px`,background:chartColors[index%chartColors.length]}}/><span className="w-full truncate text-center text-[10px] font-semibold text-slate-500" title={row.label}>{row.label}</span></div>)}</div>}
function StackedDistribution({rows}:{rows:Array<{label:string;value:number}>}){const visible=rows.slice(0,7),total=visible.reduce((sum,row)=>sum+row.value,0);return <div className="min-h-56"><div className="flex h-10 overflow-hidden rounded-md">{visible.map((row,index)=><div key={row.label} style={{width:`${percent(row.value,total)}%`,background:chartColors[index%chartColors.length]}} title={`${row.label}: ${row.value} (${percent(row.value,total)}%)`}/>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2">{visible.map((row,index)=><div key={row.label} className="flex items-center gap-2"><i className="h-3 w-3 shrink-0 rounded-sm" style={{background:chartColors[index%chartColors.length]}}/><div className="min-w-0 flex-1"><b className="block truncate text-xs">{row.label}</b><span className="text-[10px] text-slate-500">{row.value} · {percent(row.value,total)}%</span></div></div>)}</div>{!visible.length&&<p className="py-16 text-center text-xs text-slate-500">Sem dados para esta seleção.</p>}</div>}
function Technicians({rows}:{rows:ReturnType<typeof technicianRows>}){const max=Math.max(1,...rows.map(r=>r.total));return <section className="overflow-hidden border bg-[var(--ds-surface)]"><header className="border-b p-4"><h3 className="flex items-center gap-2 text-sm font-black"><Users size={17} className="text-blue-600"/>Carga e desempenho da equipe</h3><p className="mt-1 text-xs text-slate-500">Volume, resolução, SLA e tempo médio com base nos chamados filtrados.</p></header><div className="overflow-x-auto"><table className="min-w-[850px] text-left text-xs"><thead><tr><th className="px-4 py-3">Técnico</th><th className="px-4 py-3">Carga</th><th className="px-4 py-3">Ativos</th><th className="px-4 py-3">Resolvidos</th><th className="px-4 py-3">SLA vencido</th><th className="px-4 py-3">Resolução média</th></tr></thead><tbody className="divide-y">{rows.map(row=><tr key={row.name}><td className="px-4 py-3 font-black">{row.name}</td><td className="w-64 px-4 py-3"><div className="h-1.5 bg-slate-100"><div className="h-full bg-violet-500" style={{width:`${row.total/max*100}%`}}/></div></td><td className="px-4 py-3">{row.active}</td><td className="px-4 py-3 text-emerald-600">{row.resolved}</td><td className="px-4 py-3 text-red-600">{row.violated}</td><td className="px-4 py-3">{duration(row.averageResolution)}</td></tr>)}</tbody></table></div></section>}
function DetailTable({tickets,total,filter,onOpen}:{tickets:ApiChamado[];total:number;filter:MetricFilter;onOpen?:(id:number)=>void}){return <section className="overflow-hidden border bg-[var(--ds-surface)]"><header className="flex items-center justify-between border-b px-4 py-3"><div><h3 className="text-sm font-black">Detalhamento do indicador</h3><p className="mt-0.5 text-[10px] text-slate-500">{total} chamado(s) · filtro {filter}</p></div>{total>50&&<span className="text-[10px] font-bold text-amber-600">Exibindo os primeiros 50</span>}</header><div className="overflow-x-auto"><table className="min-w-[900px] text-left text-xs"><thead><tr><th className="px-4 py-3">Chamado</th><th className="px-4 py-3">Solicitante</th><th className="px-4 py-3">Área</th><th className="px-4 py-3">Responsável</th><th className="px-4 py-3">Prioridade</th><th className="px-4 py-3">SLA</th><th className="w-10"/></tr></thead><tbody className="divide-y">{tickets.map(c=><tr key={c.id} className={onOpen?"cursor-pointer":""} onClick={()=>onOpen?.(c.id)}><td className="px-4 py-3"><b className="block text-blue-600">{c.numero_chamado||`#${c.id}`}</b><span className="block max-w-64 truncate">{c.titulo}</span></td><td className="px-4 py-3">{requester(c)}</td><td className="px-4 py-3">{city(c)}</td><td className="px-4 py-3">{owner(c)}</td><td className="px-4 py-3 font-bold">{c.prioridade||"-"}</td><td className={`px-4 py-3 font-bold ${violated(c)?"text-red-600":paused(c)?"text-violet-600":"text-emerald-600"}`}>{violated(c)?"Vencido":paused(c)?"Pausado":atRisk(c)?"Em risco":"No prazo"}</td><td><ArrowRight size={15}/></td></tr>)}</tbody></table>{!tickets.length&&<p className="p-10 text-center text-xs text-slate-400">Nenhum chamado corresponde ao indicador selecionado.</p>}</div></section>}
function distribution(items:ApiChamado[],get:(c:ApiChamado)=>string){const counts=new Map<string,number>();items.forEach(c=>{const key=get(c)||"Não informado";counts.set(key,(counts.get(key)||0)+1)});return Array.from(counts,([label,value])=>({label,value})).sort((a,b)=>b.value-a.value)}
function technicianRows(items:ApiChamado[]){const map=new Map<string,ApiChamado[]>();items.forEach(c=>{const key=owner(c);map.set(key,[...(map.get(key)||[]),c])});return Array.from(map,([name,tickets])=>({name,total:tickets.length,active:tickets.filter(c=>!finalStatus(c)).length,resolved:tickets.filter(finalStatus).length,violated:tickets.filter(violated).length,averageResolution:average(tickets.filter(finalStatus).map(c=>minutes(c.criado_em,c.finalizado_em)))})).sort((a,b)=>b.active-a.active||b.total-a.total)}
function dailySeries(items:ApiChamado[],days:number){const formatter=new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit"});return Array.from({length:days},(_,index)=>{const date=new Date();date.setHours(0,0,0,0);date.setDate(date.getDate()-(days-index-1));const next=new Date(date);next.setDate(next.getDate()+1);return {label:formatter.format(date),value:items.filter(c=>{const opened=openedAt(c);return opened&&opened>=date&&opened<next}).length}})}
function statusLabel(value?:string){const status=canonicalTicketStatus(value);return {[TICKET_STATUS.OPEN]:"Em aberto",[TICKET_STATUS.IN_PROGRESS]:"Em andamento",[TICKET_STATUS.WAITING_USER]:"Aguardando usuário",[TICKET_STATUS.WAITING_THIRD_PARTY]:"Aguardando terceiros",[TICKET_STATUS.RESOLVED]:"Resolvido",[TICKET_STATUS.CLOSED]:"Concluído",[TICKET_STATUS.CANCELED]:"Cancelado",[TICKET_STATUS.REOPENED]:"Reaberto"}[status]}
