import { useMemo, useState, type ReactNode } from "react";
import { AlertTriangle, ArrowRight, Clock3, Grid2X2, List, MapPin, Monitor, Rows3, Search, Ticket, UserRound, X } from "lucide-react";
import type { ApiChamado } from "../../services/api";
import { TICKET_STATUS, canonicalTicketStatus, ticketStatusLabel } from "../../domain/ticketStatus";

type ViewMode = "table" | "compact" | "cards";
const requester=(c:ApiChamado)=>c.solicitante_nome||c.solicitante||c.email_solicitante||"Solicitante";
const responsible=(c:ApiChamado)=>c.responsavel_nome||c.responsavel||"Sem responsável";
function date(value?:string|null){if(!value)return "-";const parsed=new Date(value);return Number.isNaN(parsed.getTime())?"-":new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(parsed)}
const location=(c:ApiChamado)=>[c.municipio_solicitante,c.unidade_solicitante].filter(Boolean).join(" · ")||"Origem não informada";
const serviceLocation=(c:ApiChamado)=>[c.ativo_municipio||c.municipio_solicitante,c.ativo_unidade||c.unidade_solicitante].filter(Boolean).join(" · ")||"Local não informado";
const asset=(c:ApiChamado)=>c.ativo_id?[c.ativo_hostname||"Ativo",c.ativo_patrimonio||`#${c.ativo_id}`].filter(Boolean).join(" · "):"Nenhum ativo relacionado";
function priorityClass(value?:string|null){const p=String(value||"").toLowerCase();if(p.includes("crít"))return "border-rose-200 bg-rose-50 text-rose-700";if(p==="alta")return "border-red-200 bg-red-50 text-red-700";if(p==="baixa")return "border-emerald-200 bg-emerald-50 text-emerald-700";return "border-amber-200 bg-amber-50 text-amber-700"}
function statusClass(value?:string|null){const s=canonicalTicketStatus(value);if(s===TICKET_STATUS.CLOSED||s===TICKET_STATUS.RESOLVED)return "border-emerald-200 bg-emerald-50 text-emerald-700";if(s===TICKET_STATUS.IN_PROGRESS)return "border-amber-200 bg-amber-50 text-amber-700";if(s===TICKET_STATUS.WAITING_USER||s===TICKET_STATUS.WAITING_THIRD_PARTY)return "border-violet-200 bg-violet-50 text-violet-700";return "border-blue-200 bg-blue-50 text-blue-700"}
function Badge({children,className=""}:{children:ReactNode;className?:string}){return <span className={`inline-flex min-h-6 items-center border px-2 py-0.5 text-[10px] font-black ${className}`}>{children}</span>}

export function ChamadosListModule({chamados,onOpen,dark=false}:{chamados:ApiChamado[];onOpen:(id:number)=>void;dark?:boolean}){
  const [search,setSearch]=useState("");
  const [view,setView]=useState<ViewMode>(()=>{const saved=localStorage.getItem("smart_helpdesk_ticket_list_view");return saved==="compact"||saved==="cards"?saved:"table"});
  const [selectedId,setSelectedId]=useState<number|null>(null);
  const selected=chamados.find(item=>Number(item.id)===selectedId)||null;
  const filtered=useMemo(()=>{const query=search.trim().toLocaleLowerCase("pt-BR");if(!query)return chamados;return chamados.filter(item=>[item.numero_chamado,item.titulo,requester(item),responsible(item),item.status,item.prioridade,item.municipio_solicitante,item.unidade_solicitante,item.ativo_hostname,item.ativo_patrimonio].some(value=>String(value||"").toLocaleLowerCase("pt-BR").includes(query)))},[chamados,search]);
  function chooseView(next:ViewMode){setView(next);localStorage.setItem("smart_helpdesk_ticket_list_view",next)}
  const surface=dark?"border-white/10 bg-white/[0.035]":"border-zinc-200 bg-white",muted=dark?"text-white/50":"text-zinc-500",hover=dark?"hover:bg-white/5":"hover:bg-blue-50/50";
  return <section className="ticket-list-workspace min-h-0">
    <header className={`flex flex-wrap items-center gap-3 border-b border-t px-4 py-3 ${surface}`}>
      <div className="min-w-0 flex-1"><h3 className="text-sm font-black">Todos os chamados</h3><p className={`mt-0.5 text-xs ${muted}`}>Identifique solicitante, origem, atendimento e ativo sem sair da lista.</p></div>
      <label className={`ds-search flex h-10 min-w-[260px] flex-1 items-center gap-2 border px-3 lg:max-w-[420px] ${surface}`}><Search size={16} className={muted}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar chamado, usuário, cidade ou ativo..." className="min-w-0 flex-1 bg-transparent text-sm outline-none"/>{search&&<button type="button" onClick={()=>setSearch("")} aria-label="Limpar pesquisa"><X size={15}/></button>}</label>
      <div className={`flex h-10 items-center border p-1 ${surface}`} aria-label="Modo de visualização">{([["table",List,"Tabela"],["compact",Rows3,"Compacta"],["cards",Grid2X2,"Cards"]] as const).map(([id,Icon,label])=><button key={id} type="button" onClick={()=>chooseView(id)} title={label} aria-pressed={view===id} className={`grid h-8 w-9 place-items-center transition ${view===id?"bg-blue-600 text-white":muted}`}><Icon size={15}/></button>)}</div>
      <Badge className="border-zinc-200 bg-zinc-50 text-zinc-700">{filtered.length} chamado(s)</Badge>
    </header>
    <div className={`grid min-h-[560px] border-b ${surface} ${selected?"xl:grid-cols-[minmax(0,1fr)_390px]":"grid-cols-1"}`}>
      <div className="min-w-0 overflow-auto">
        {view==="table"&&<div className="min-w-[1040px]">
          <div className={`grid grid-cols-[135px_minmax(280px,1fr)_180px_170px_150px_120px_28px] gap-3 border-b px-4 py-2.5 text-[10px] font-black uppercase tracking-wider ${muted}`}><span>Chamado</span><span>Assunto / origem</span><span>Solicitante</span><span>Ativo / atendimento</span><span>Status</span><span>Prioridade / SLA</span><span/></div>
          <div className={dark?"divide-y divide-white/10":"divide-y divide-zinc-100"}>{filtered.map(item=><button key={item.id} type="button" onClick={()=>setSelectedId(Number(item.id))} onDoubleClick={()=>onOpen(item.id)} className={`grid w-full grid-cols-[135px_minmax(280px,1fr)_180px_170px_150px_120px_28px] items-center gap-3 px-4 py-3 text-left transition ${hover} ${selectedId===Number(item.id)?dark?"bg-blue-500/10":"bg-blue-50":""}`}>
            <span className="text-xs font-black text-blue-600">{item.numero_chamado||`#${item.id}`}</span><span className="min-w-0"><b className="block truncate text-sm">{item.titulo}</b><small className={`mt-1 flex items-center gap-1 truncate ${muted}`}><MapPin size={11}/>{location(item)} · {date(item.criado_em)}</small></span><span className="min-w-0"><b className="block truncate text-xs">{requester(item)}</b><small className={`block truncate ${muted}`}>{item.departamento||item.setor||"Sem departamento"}</small></span><span className="min-w-0"><b className={`block truncate text-xs ${item.ativo_id?"text-emerald-600":""}`}>{asset(item)}</b><small className={`block truncate ${muted}`}>{serviceLocation(item)}</small></span><span><Badge className={statusClass(item.status)}>{ticketStatusLabel(item.status)}</Badge></span><span className="flex items-center gap-1.5"><Badge className={priorityClass(item.prioridade)}>{item.prioridade||"Normal"}</Badge>{item.vencido&&<AlertTriangle size={15} className="text-red-500"/>}</span><ArrowRight size={16} className={muted}/>
          </button>)}</div>
        </div>}
        {view==="compact"&&<div className={dark?"divide-y divide-white/10":"divide-y divide-zinc-100"}>{filtered.map(item=><button key={item.id} type="button" onClick={()=>setSelectedId(Number(item.id))} onDoubleClick={()=>onOpen(item.id)} className={`flex w-full items-center gap-3 px-4 py-2.5 text-left ${hover}`}><Ticket size={16} className="shrink-0 text-blue-600"/><b className="w-32 shrink-0 text-xs text-blue-600">{item.numero_chamado||`#${item.id}`}</b><span className="min-w-0 flex-1 truncate text-sm font-bold">{item.titulo}</span><span className={`hidden w-44 truncate text-xs md:block ${muted}`}>{requester(item)}</span><span className={`hidden w-44 truncate text-xs lg:block ${muted}`}><MapPin size={11} className="mr-1 inline"/>{location(item)}</span><Badge className={statusClass(item.status)}>{ticketStatusLabel(item.status)}</Badge><ArrowRight size={15} className={muted}/></button>)}</div>}
        {view==="cards"&&<div className="grid gap-px bg-zinc-200/70 md:grid-cols-2 2xl:grid-cols-3">{filtered.map(item=><button key={item.id} type="button" onClick={()=>setSelectedId(Number(item.id))} onDoubleClick={()=>onOpen(item.id)} className={`min-h-48 p-4 text-left ${dark?"bg-slate-900 hover:bg-slate-800":"bg-white hover:bg-blue-50/50"}`}><div className="flex items-start justify-between gap-3"><span><b className="block text-xs text-blue-600">{item.numero_chamado||`#${item.id}`}</b><strong className="mt-1 block line-clamp-2 text-sm">{item.titulo}</strong></span><Badge className={priorityClass(item.prioridade)}>{item.prioridade||"Normal"}</Badge></div><div className={`mt-4 space-y-2 text-xs ${muted}`}><p className="flex gap-2"><UserRound size={14}/>{requester(item)}</p><p className="flex gap-2"><MapPin size={14}/>{location(item)}</p><p className="flex gap-2"><Monitor size={14}/>{asset(item)}</p></div><div className="mt-4 flex items-center justify-between"><Badge className={statusClass(item.status)}>{ticketStatusLabel(item.status)}</Badge><span className={`text-[11px] ${item.vencido?"font-black text-red-600":muted}`}>{item.vencido?"SLA vencido":date(item.criado_em)}</span></div></button>)}</div>}
        {!filtered.length&&<div className="ds-empty-state min-h-[380px]"><Ticket className="ds-empty-state__icon"/><strong>Nenhum chamado encontrado</strong><p>Ajuste a pesquisa ou os filtros da central de atendimento.</p></div>}
      </div>
      {selected&&<aside className={`border-l ${surface}`} aria-label="Pré-visualização do chamado"><div className="sticky top-0">
        <header className="flex items-start gap-3 border-b p-4"><span className="grid h-9 w-9 shrink-0 place-items-center bg-blue-50 text-blue-600"><Ticket size={17}/></span><div className="min-w-0 flex-1"><p className="text-[11px] font-black text-blue-600">{selected.numero_chamado||`#${selected.id}`}</p><h3 className="mt-1 text-base font-black leading-5">{selected.titulo}</h3></div><button type="button" onClick={()=>setSelectedId(null)} className={`grid h-8 w-8 place-items-center ${muted}`} aria-label="Fechar pré-visualização"><X size={17}/></button></header>
        <div className="divide-y p-4 pt-2"><PreviewRow icon={<UserRound/>} label="Solicitante" value={requester(selected)} detail={selected.departamento||selected.setor||"Sem departamento"}/><PreviewRow icon={<MapPin/>} label="Origem / área" value={location(selected)}/><PreviewRow icon={<MapPin/>} label="Local do atendimento" value={serviceLocation(selected)}/><PreviewRow icon={<Monitor/>} label="Ativo relacionado" value={asset(selected)} detail={selected.ativo_id?selected.ativo_municipio||undefined:undefined}/><PreviewRow icon={<UserRound/>} label="Responsável" value={responsible(selected)}/><PreviewRow icon={<Clock3/>} label="Abertura e SLA" value={date(selected.criado_em)} detail={selected.vencido?"SLA vencido":selected.sla_status==="pausado"?"SLA pausado":"SLA em acompanhamento"} danger={Boolean(selected.vencido)}/></div>
        <div className="flex flex-wrap gap-2 border-t p-4"><Badge className={statusClass(selected.status)}>{ticketStatusLabel(selected.status)}</Badge><Badge className={priorityClass(selected.prioridade)}>{selected.prioridade||"Normal"}</Badge></div><div className="border-t p-4"><button type="button" onClick={()=>onOpen(selected.id)} className="ds-button ds-button--primary flex w-full items-center justify-center gap-2">Abrir chamado completo <ArrowRight size={16}/></button><p className={`mt-2 text-center text-[10px] ${muted}`}>Duplo clique em uma linha também abre o chamado.</p></div>
      </div></aside>}
    </div>
  </section>
}

function PreviewRow({icon,label,value,detail,danger=false}:{icon:ReactNode;label:string;value:string;detail?:string;danger?:boolean}){return <div className="flex gap-3 py-3"><span className="mt-0.5 text-blue-600 [&>svg]:h-4 [&>svg]:w-4">{icon}</span><span className="min-w-0"><small className="block text-[10px] font-black uppercase tracking-wider text-zinc-400">{label}</small><b className={`mt-0.5 block text-sm ${danger?"text-red-600":""}`}>{value}</b>{detail&&<span className={`mt-0.5 block text-xs ${danger?"font-bold text-red-600":"text-zinc-500"}`}>{detail}</span>}</span></div>}
